### ISSUE TITLE
[Bug] Development switchover between multiple platforms is abnormal：RelayCommand 

### ISSUE THREAD

**Issue by one966** [CommunityToolkit/dotnet#392] opened 2022-08-19 13:42 UTC
### Description

RelayCommand Uses the create command
When I was developing in the Window environment, I wrote two commands and they ran normally. However, when I switched to the Android platform and then switched to the Window environment, there would be problems with these commands.
### Stack Trace

Type "Alert GalleryViewModel" already contains the definition of "toastJSfCommand"

### Link to Reproduction Sample

 ```csharp
[ObservableProperty]
string msg="what this？";

[ObservableProperty]
string title = "toast？";

//public ICommand toastJSfCom { get; private set; }
public `AlertsGalleryViewModel()`
{
    //toastJSfCom =new Command(()=>{ toastJSf(); });
}

[RelayCommand]
async void toastJSf()
{
    CancellationTokenSource cancellationTokenSource = new CancellationTokenSource();
    string text = "This is a Toast";
    ToastDuration duration = ToastDuration.Short;
    double fontSize = 14;
    title="why";
    var toast = Toast.Make(text, duration, fontSize);

    await toast.Show(cancellationTokenSource.Token);
}


[RelayCommand]
async void   ShowMsg()
{
    CancellationTokenSource cancellationTokenSource = new CancellationTokenSource();

    var options = new SnackbarOptions
    {
        BackgroundColor = Colors.Red,
        TextColor = Colors.Green,
        ActionButtonTextColor = Colors.Yellow,
        CornerRadius = new CornerRadius(10),
        Font = Font.SystemFontOfSize(14),
    };

  var  customSnackbar = Snackbar.Make(
        "This is a customized Snackbar",
        async () =>
        {
            await Task.Delay(1000);
            Msg="change";
        },
        "Change Button Color",
        TimeSpan.FromSeconds(30),
        options);

    await customSnackbar.Show();
}
```

**Comment by Sergio0694** [comment] 2022-08-19 16:56
Hey @one966, are you on WPF?
This seems like a duplicate of #343, can you try the workaround suggested here?
That is: https://github.com/dotnet/wpf/issues/6792#issuecomment-1183633402.

**Comment by one966** [comment] 2022-08-20 14:40
> I think this is an issue on the MVVM toolkit and not the MAUI toolkit. Can we transfer issues between these repos?

yes ，this is an issue mvvm toolkit 。

**Comment by one966** [comment] 2022-08-20 14:40
> Hey @one966, are you on WPF? This seems like a duplicate of #343, can you try the workaround suggested here? That is: [dotnet/wpf#6792 (comment)](https://github.com/dotnet/wpf/issues/6792#issuecomment-1183633402).



> Hey @one966, are you on WPF? This seems like a duplicate of #343, can you try the workaround suggested here? That is: [dotnet/wpf#6792 (comment)](https://github.com/dotnet/wpf/issues/6792#issuecomment-1183633402).

no ，is MAUI ，i use  MVVM toolkit

**Closed** 2022-08-20 15:12 UTC
Labels: needs author feedback :memo:, mvvm-toolkit :toolbox:, bug
