### ISSUE TITLE
Using the latest version of CommunityToolkit.Mvvm in a WinUI project targeting .NET 8 generates a slew of warnings

### ISSUE THREAD

**Issue by egvijayanand** [CommunityToolkit/dotnet#930] opened 2024-08-29 20:30 UTC
### Describe the bug

Using the latest version (v8.3.0) of CommunityToolkit.Mvvm in a WinUI project targeting .NET 8 with the stable version of the WindowsAppSdk generates a slew of warnings.

Refer to the additional context for the build log.

### Regression

Yes, working fine with v8.2.2

### Steps to reproduce

```text
1. Create a new WinUI project targeting .NET 8 with the stable version of WindowsAppSdk
2. Add a reference to the latest version of CommunityToolkit.Mvvm package (v8.3.0)
3. Build the app
```

### Expected behavior

It should not generate any warnings quite like the earlier release v8.2.2

### IDE and version

Other

### IDE version

CLI

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.3.0

### Additional context

C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277: Found conflicts between differ
ent versions of "WinRT.Runtime" that could not be resolved. [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277: There was a conflict between "
WinRT.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" and "WinRT.Runtime, Version=2.1.0.0, Culture=neutr
al, PublicKeyToken=99ea127f02d97709". [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:     "WinRT.Runtime, Version=2.
0.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" was chosen because it was primary and "WinRT.Runtime, Version=2.1.0.0, Cult
ure=neutral, PublicKeyToken=99ea127f02d97709" was not. [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:     References which depend on
 "WinRT.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" [D:\NuGet\packages\microsoft.windows.sdk.net.ref
\10.0.19041.34\lib\net6.0\WinRT.Runtime.dll]. [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\micr
osoft.windows.sdk.net.ref\10.0.19041.34\lib\net6.0\WinRT.Runtime.dll [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\microsoft.windows.sdk.net.ref\10.0.19041.34\lib\net6.0\WinRT.Runtime.dll". [E:\MyAp
p\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windows.sdk.net.ref\10.0.19041.34\lib/net6.0/WinRT.Runtime.dll [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:     References which depend on
 or have been unified to "WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" []. [E:\MyApp\MyApp.cspr
oj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\comm
unitytoolkit.mvvm\8.3.0\lib\net8.0-windows10.0.17763\CommunityToolkit.Mvvm.dll [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\communitytoolkit.mvvm\8.3.0\lib\net8.0-windows10.0.17763\CommunityToolkit.Mvvm.dll"
. [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
communitytoolkit.mvvm\8.3.0\lib\net8.0-windows10.0.17763\CommunityToolkit.Mvvm.dll [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\micr
osoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.InteractiveExperiences.Projection.dll [E:\MyApp\MyApp.csp
roj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Inte
ractiveExperiences.Projection.dll". [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.InteractiveExperiences.Projection.dll [E:\MyApp\MyApp
.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI.dll [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\micr
osoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI.dll [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.WinU
I.dll". [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI.dll [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\micr
osoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppLifecycle.Projection.dll [E:\MyApp\MyApp.cspro
j]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Wind
ows.AppLifecycle.Projection.dll". [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppLifecycle.Projection.dll [E:\MyApp\MyApp.c
sproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\micr
osoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Builder.Projection.dll [E:\MyApp
\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Wind
ows.AppNotifications.Builder.Projection.dll". [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Builder.Projection.dll [E:\M
yApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\micr
osoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Projection.dll [E:\MyApp\MyApp.c
sproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Wind
ows.AppNotifications.Projection.dll". [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Projection.dll [E:\MyApp\MyA
pp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Builder.Projection.dll [E:\M
yApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\micr
osoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.dll
 [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Wind
ows.ApplicationModel.DynamicDependency.Projection.dll". [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.DynamicDependency.Projection
.dll [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Management.Deployment.Projection.dll [E:\MyAp
p\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\micr
osoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.Resources.Projection.dll [E:\MyA
pp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Wind
ows.ApplicationModel.Resources.Projection.dll". [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.Resources.Projection.dll [E:
\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI.dll [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\micr
osoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll
 [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Wind
ows.ApplicationModel.WindowsAppRuntime.Projection.dll". [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection
.dll [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\micr
osoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Management.Deployment.Projection.dll [E:\MyApp\My
App.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Wind
ows.Management.Deployment.Projection.dll". [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Management.Deployment.Projection.dll [E:\MyAp
p\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\micr
osoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.PushNotifications.Projection.dll [E:\MyApp\MyApp.
csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Wind
ows.PushNotifications.Projection.dll". [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.PushNotifications.Projection.dll [E:\MyApp\My
App.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\micr
osoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Security.AccessControl.Projection.dll [E:\MyApp\M
yApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Wind
ows.Security.AccessControl.Projection.dll". [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Security.AccessControl.Projection.dll [E:\MyA
pp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\micr
osoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Power.Projection.dll [E:\MyApp\MyApp.cspro
j]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Wind
ows.System.Power.Projection.dll". [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Power.Projection.dll [E:\MyApp\MyApp.c
sproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\micr
osoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Projection.dll [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Wind
ows.System.Projection.dll". [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Projection.dll [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         D:\NuGet\packages\micr
osoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Widgets.Projection.dll [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item in
cludes which caused reference "D:\NuGet\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Wind
ows.Widgets.Projection.dll". [E:\MyApp\MyApp.csproj]
C:\Program Files\dotnet\sdk\8.0.400\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\NuGet\packages\
microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Widgets.Projection.dll [E:\MyApp\MyApp.csproj
]

### Help us help you

No, just wanted to report this

**Comment by egvijayanand** [comment] 2024-08-29 20:31
Not only WinUI projects but also .NET MAUI projects, as it uses WindowsAppSdk for its Windows platform target.

**Comment by Sergio0694** [comment] 2024-08-29 21:35
Duplicate of #923, the workaround is in https://github.com/CommunityToolkit/dotnet/issues/923#issuecomment-2314444048 🙂

The issue is you're using a .NET SDK that's not been updated yet with the new Windows SDK projections.

**Closed** 2024-08-29 21:36 UTC
Labels: duplicate :busts_in_silhouette:
