### ISSUE TITLE
TypeExtensions.ToTypeString throws exception for open generic types

### ISSUE THREAD

**Issue by mikechristiansenvae** [CommunityToolkit/dotnet#609] opened 2023-02-15 17:23 UTC
### Describe the bug

`TypeExtensions.ToTypeString` throws an `ArgumentOutOfRangeException` for open generic types.

[Example on .NET Fiddle](https://dotnetfiddle.net/7Usl8S)

### Steps to reproduce

1. Run the following code:

```csharp
using CommunityToolkit.Diagnostics;
System.Console.WriteLine(typeof(Foo<>).ToTypeString());
public sealed record Foo<T>;
```

2. Observe the exception is thrown

```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at CommunityToolkit.Diagnostics.TypeExtensions.<ToTypeString>g__FormatDisplayString|2_0(Type type, Int32 genericTypeOffset, ReadOnlySpan`1 typeArguments) in /_/src/CommunityToolkit.Diagnostics/Extensions/TypeExtensions.cs:line 110
   at CommunityToolkit.Diagnostics.TypeExtensions.<ToTypeString>g__FormatDisplayString|2_0(Type type, Int32 genericTypeOffset, ReadOnlySpan`1 typeArguments) in /_/src/CommunityToolkit.Diagnostics/Extensions/TypeExtensions.cs:line 131
   at CommunityToolkit.Diagnostics.TypeExtensions.<>c.<ToTypeString>b__2_3(Type t) in /_/src/CommunityToolkit.Diagnostics/Extensions/TypeExtensions.cs:line 114
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at CommunityToolkit.Diagnostics.TypeExtensions.<ToTypeString>g__FormatDisplayString|2_0(Type type, Int32 genericTypeOffset, ReadOnlySpan`1 typeArguments) in /_/src/CommunityToolkit.Diagnostics/Extensions/TypeExtensions.cs:line 114
   at CommunityToolkit.Diagnostics.TypeExtensions.<>c.<ToTypeString>b__2_1(Type t) in /_/src/CommunityToolkit.Diagnostics/Extensions/TypeExtensions.cs:line 164
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValueLocked(TKey key, CreateValueCallback createValueCallback)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
   at CommunityToolkit.Diagnostics.TypeExtensions.ToTypeString(Type type) in /_/src/CommunityToolkit.Diagnostics/Extensions/TypeExtensions.cs:line 138
   at Program.<Main>$(String[] args)
Command terminated by signal 6
```

### Expected behavior

`typeof(Foo<>).ToTypeString()` should produce the text `Foo<>`

### IDE and version

Rider

### IDE version

#RD-223.8617.53

### Nuget packages

- [ ] CommunityToolkit.Common
- [X] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [ ] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.1.0

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment] 2023-03-12 19:01
Duplicate of #390.

**Closed by Sergio0694** 2023-03-12 19:01 UTC
Labels: bug :bug:, duplicate :busts_in_silhouette:, mvvm-toolkit :toolbox:
