### ISSUE TITLE
Add support for setter protection level for ObservableProperty

### ISSUE THREAD

**Issue by sensslen** [CommunityToolkit/dotnet#758] opened 2023-09-11 08:38 UTC
### Overview

When using the [ObservableProperty] attribute to generate the code for the observable property, the protection level of the generated setter is always public

### API breakdown

```csharp
public enum SetterProtection
{
    Public,
    Protected,
    Private
}


[ObservableProperty(SetterProtection = SetterProtection.Private)]
private int _someValue;
```

### Usage example

```csharp
[ObservableProperty(SetterProtection = SetterProtection.Private)]
private int _someValue;
```

### Breaking change?

No

### Alternatives

I am not aware of any

### Additional context

I do quite often want to provide readonly properties for binding in xaml. These properties should not be set from xaml. While I can make sure this is how things are done, I don't get any support from the Toolkit (and if the xaml is wrong and sets such a property, It will silently work instead of causing a binding error).

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment] 2023-09-11 11:24
Duplicate of #291.
Superseded by #555.

**Closed by Sergio0694** 2023-09-11 11:24 UTC
Labels: duplicate :busts_in_silhouette:, feature request :mailbox_with_mail:, mvvm-toolkit :toolbox:
