### ISSUE TITLE
Multiple definitions

### ISSUE THREAD

**Issue by NebojsaMancic** [CommunityToolkit/dotnet#437] opened 2022-09-12 00:05 UTC
### Describe the bug

I have installed nuget package and added [ObservableObject] to my ViewModel class. When I have build app, I have a lot of error messages for duplicated items

My ViewModel class looks like this

    [ObservableObject]
    public partial class KalkulacijaViewModel 
    {

        [ObservableProperty]
        private int velicinaFonta;
        public KalkulacijaViewModel()
        {
        }
}

and errors are 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0102	The type 'KalkulacijaViewModel' already contains a definition for 'PropertyChanged'	Sara	C:\Users\Manca\source\repos6\Softman22\Sara\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservableObjectGenerator\Sara.ViewModels.Nabavka.KalkulacijaViewModel.g.cs	11	Active
Error	CS0102	The type 'KalkulacijaViewModel' already contains a definition for 'PropertyChanging'	Sara	C:\Users\Manca\source\repos6\Softman22\Sara\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservableObjectGenerator\Sara.ViewModels.Nabavka.KalkulacijaViewModel.g.cs	15	Active
Error	CS0111	Type 'KalkulacijaViewModel' already defines a member called 'OnPropertyChanged' with the same parameter types	Sara	C:\Users\Manca\source\repos6\Softman22\Sara\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservableObjectGenerator\Sara.ViewModels.Nabavka.KalkulacijaViewModel.g.cs	22	Active
Error	CS0111	Type 'KalkulacijaViewModel' already defines a member called 'OnPropertyChanging' with the same parameter types	Sara	C:\Users\Manca\source\repos6\Softman22\Sara\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservableObjectGenerator\Sara.ViewModels.Nabavka.KalkulacijaViewModel.g.cs	33	Active
Error	CS0111	Type 'KalkulacijaViewModel' already defines a member called 'OnPropertyChanged' with the same parameter types	Sara	C:\Users\Manca\source\repos6\Softman22\Sara\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservableObjectGenerator\Sara.ViewModels.Nabavka.KalkulacijaViewModel.g.cs	44	Active
Error	CS0111	Type 'KalkulacijaViewModel' already defines a member called 'OnPropertyChanging' with the same parameter types	Sara	C:\Users\Manca\source\repos6\Softman22\Sara\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservableObjectGenerator\Sara.ViewModels.Nabavka.KalkulacijaViewModel.g.cs	55	Active
Error	CS0111	Type 'KalkulacijaViewModel' already defines a member called 'SetProperty' with the same parameter types	Sara	C:\Users\Manca\source\repos6\Softman22\Sara\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservableObjectGenerator\Sara.ViewModels.Nabavka.KalkulacijaViewModel.g.cs	76	Active
Error	CS0111	Type 'KalkulacijaViewModel' already defines a member called 'SetProperty' with the same parameter types	Sara	
 ....

All duplicated members are in .g.cs file

### Steps to reproduce

```text
build app
```

### Expected behavior

My code without duplicated members.

### IDE and version

VS 2022

### IDE version

17.3.3

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment] 2022-09-12 02:36
Duplicate of #343.

**Closed by Sergio0694** 2022-09-12 02:36 UTC
Labels: duplicate :busts_in_silhouette:, external :arrow_heading_up:, mvvm-toolkit :toolbox:
