### ISSUE TITLE
[ObservableProperty] - error CS0103: The name '{Property}' does not exist in the current context

### ISSUE THREAD

**Issue by lemonlad** [CommunityToolkit/dotnet#330] opened 2022-07-01 11:06 UTC
### Describe the bug

I receive the build-time error:

``` CS0103: The name '{Property}' does not exist in the current context upon building when using [ObservableProperty] and trying to set the generated property```

```csharp

namespace WpfApp1_TestMVVMToolKit.ViewModels
{
    public partial class MainWindowViewModel : ObservableObject
    {
        [ObservableProperty]
        private string title;

        private void DoSomething()
        {

            Title = "a";
        }
    }

}
```

### Steps to reproduce

-  Create WPF App (.NET Framework 4.7.2)
- Add package CommunityToolkit.Mvvm 8.0.0-preview4
- Add below code to a class

```csharp
namespace WpfApp1_TestMVVMToolKit.ViewModels
{
    public partial class MainWindowViewModel : ObservableObject
    {
        [ObservableProperty]
        private string title;

        private void DoSomething()
        {

            Title = "a";
        }
    }

}
```

Build, build fails with error:

```error CS0103: The name 'Title' does not exist in the current context```

Intellisense does not pick up that Title property exists

Roll back to CommunityToolkit.Mvvm 7.1.2

Build, fails with error:

```error CS0103: The name 'Title' does not exist in the current context```

In 7.1.2, although build still fails, intellisense does pick up that the Title property exists, with generated code as below:

```csharp
namespace WpfApp1_TestMVVMToolKit.ViewModels
{
    public partial class MainWindowViewModel
    {
        [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "7.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public string Title
        {
            get => title;
            set
            {
                if (!global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(title, value))
                {
                    OnPropertyChanging(global::CommunityToolkit.Mvvm.ComponentModel.__Internals.__KnownINotifyPropertyChangedOrChangingArgs.TitlePropertyChangingEventArgs);
                    title = value;
                    OnPropertyChanged(global::CommunityToolkit.Mvvm.ComponentModel.__Internals.__KnownINotifyPropertyChangedOrChangingArgs.TitlePropertyChangedEventArgs);
                }
            }
        }
    }
}

```

### Expected behavior

I expect to be able to use the generated Title property, and for OnPropertyChanged to fire automatically when changing the value

### IDE and version

VS 2022

### IDE version

17.2.3

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

7.1.2, 8.0.0-preview4

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment] 2022-07-01 11:20
Duplicate of #158, this is a known issue with .NET Framework non-SDK-style WPF projects.
You'll have to either move that code to a .NET Standard library, or upgrade to an SDK-style .NET 6 WPF project.

**Closed by Sergio0694** 2022-07-01 11:20 UTC
Labels: bug :bug:

**Comment by mklemarczyk** [comment] 2024-12-14 13:21
@Sergio0694 it does not work in last .NET 9 with project in SDK style WPF project.
