### ISSUE TITLE
ObservableValidator auto-generated Error

### ISSUE THREAD

**Issue by TianMaiChengGhostRidder** [CommunityToolkit/dotnet#445] opened 2022-09-19 02:52 UTC
### Describe the bug

If I use Microsoft. Toolkit The Mvvm library will not fail. If I use the Community Toolkit MVVM, an error is reported. The IDE is VS2022
![图片](https://user-images.githubusercontent.com/51288333/190942404-bf7e93c4-9647-4e0a-932a-423b6adcf9dd.png)

### Regression

8.0.0

### Steps to reproduce

```text
Even a simple file can go wrong
```

### Expected behavior

Error “global::System.CodeDom.Compiler.GeneratedCode”特性重复	MvvmToolkitValidationSample	C:\Users\Administrator\Downloads\MvvmToolkitValidationSample-main\src\MvvmToolkitValidationSample\MvvmToolkitValidationSample\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservableValidatorValidateAllPropertiesGenerator\__ObservableValidatorExtensions.g.cs	5	
Error	CS0579	“global::System.ComponentModel.EditorBrowsable”特性重复	MvvmToolkitValidationSample	C:\Users\Administrator\Downloads\MvvmToolkitValidationSample-main\src\MvvmToolkitValidationSample\MvvmToolkitValidationSample\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservableValidatorValidateAllPropertiesGenerator\__ObservableValidatorExtensions.g.cs	8	

……………………………………………………………………
………………………………………………
balabala

### IDE and version

VS 2022, VS 2022 Preview

### IDE version

VS2022

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by mikechristiansenvae** [comment] 2022-09-19 17:22
I can't read the Chinese (Japanese?), but I **think** this is a duplicate of https://github.com/CommunityToolkit/dotnet/issues/343

[This workaround](https://github.com/dotnet/wpf/issues/6792#issuecomment-1183633402) worked for me.

**Comment by Sergio0694** [comment] 2022-10-23 11:19
This does indeed just seem to be a duplicate of that and it's fixed now with the new SDK. Thank you! 🙂

**Closed by Sergio0694** 2022-10-23 11:19 UTC
Labels: bug :bug:
