### ISSUE TITLE
Implementing IRecipient<> gives build error

### ISSUE THREAD

**Issue by fatichar** [CommunityToolkit/dotnet#400] opened 2022-08-24 22:34 UTC
### Describe the bug

On version 8.0.0, implementing IRecipient<> interface gives build errors. One of the errors is:

```
Error	CS0111	Type '__IMessengerExtensions' already defines a member called 'CreateAllMessagesRegistrator' with the same parameter types	App	P:\Projects\KafkaLens\App\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.IMessengerRegisterAllGenerator\KafkaLens.App.Controls.Browser.g.cs	9	Active
```

### Regression

7.1.2

### Steps to reproduce

```text
1. Install version 8.0.0 of the package
2. Create a class and implement IRecipient<object>
2. Build the project using VS2022
```

### Expected behavior

Build should succeed

### Screenshots

<img width="615" alt="image" src="https://user-images.githubusercontent.com/10287054/186535268-1f01015e-5bf0-40fc-9ab9-e25b6e449408.png">

### IDE and version

VS 2022, VS 2022 Preview

### IDE version

17.3.0 Preview 4.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Help us help you

No, just wanted to report this

**Comment by michael-hawker** [comment] 2022-08-25 21:56
@fatichar is this a WPF project? This smells like a duplicate of the issue in the WPF tooling here: https://github.com/dotnet/wpf/issues/6792

**Comment by fatichar** [comment] 2022-08-26 03:30
Yes, a WPF App. Looks like the same issue you mentioned. Will close.

**Closed** 2022-08-26 03:31 UTC
Labels: bug :bug:
