### ISSUE TITLE
Source generator diplication

### ISSUE THREAD

**Issue by eduardoagr** [CommunityToolkit/dotnet#401] opened 2022-08-25 19:54 UTC
### Describe the bug

When I declare a field on my ViewModel, with the attribute "ObservableProperty", it will generate duplicates, an not run

### Steps to reproduce

```text
1. Create a WPF application
2. Install the .Net community toolkit
3. Crete your ViewModel as partial
4. Create a property. ex: _isVisile and don't forget to add the ObservableProperty attribute
5. Define an xmlns in your XAML to point to your VM folder 
6. Point the DataContext to the VM
```

### Expected behavior

The TextBox would disappear

### Screenshots

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/6854010/186755366-15e14eeb-5752-4245-9b91-d498652ce3ff.png">

<img width="991" alt="image" src="https://user-images.githubusercontent.com/6854010/186755458-ad396f93-514a-4095-8d79-95b6ac990f2c.png">
 
<img width="288" alt="image" src="https://user-images.githubusercontent.com/6854010/186755546-d142464a-5ba9-4bed-9cbd-e8002e65cc94.png">

### IDE and version

VS 2022

### IDE version

Version 17.3.2

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0

### Help us help you

No, just wanted to report this

**Comment by michael-hawker** [comment] 2022-08-25 21:55
@eduardoagr is this a WPF project? There was an issue with the WPF tooling. So can you clarify if this is a duplicate of that issue or something else? https://github.com/dotnet/wpf/issues/6792

**Comment by eduardoagr** [comment] 2022-08-25 21:58
@michael-hawker yes is a WPF, and is not related to the https://github.com/dotnet/wpf/issues/6792, since I am not in 17.2.6

**Comment by dpaulino** [comment] 2022-08-26 15:50
I'm having similar issues with Ambie

![image](https://user-images.githubusercontent.com/7649589/186943843-8c8635a1-800c-4b4f-bf56-54f0522f62a1.png)

```
1>C:\Users\kid_j\source\repos\ambie\src\AmbientSounds\Microsoft.Toolkit.Mvvm.SourceGenerators\Microsoft.Toolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullAttribute.cs(15,27,15,43): error CS0101: The namespace 'System.Diagnostics.CodeAnalysis' already contains a definition for 'NotNullAttribute'
1>C:\Users\kid_j\source\repos\ambie\src\AmbientSounds\Microsoft.Toolkit.Mvvm.SourceGenerators\Microsoft.Toolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute.cs(14,27,14,52): error CS0101: The namespace 'System.Diagnostics.CodeAnalysis' already contains a definition for 'NotNullIfNotNullAttribute'
1>C:\Users\kid_j\source\repos\ambie\src\AmbientSounds\Microsoft.Toolkit.Mvvm.SourceGenerators\Microsoft.Toolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute.cs(13,6,13,20): error CS0579: Duplicate 'AttributeUsage' attribute
1>C:\Users\kid_j\source\repos\ambie\src\AmbientSounds\Microsoft.Toolkit.Mvvm.SourceGenerators\Microsoft.Toolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullAttribute.cs(14,6,14,20): error CS0579: Duplicate 'AttributeUsage' attribute
1>C:\Users\kid_j\source\repos\ambie\src\AmbientSounds\Microsoft.Toolkit.Mvvm.SourceGenerators\Microsoft.Toolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute.cs(20,16,20,41): error CS0111: Type 'NotNullIfNotNullAttribute' already defines a member called 'NotNullIfNotNullAttribute' with the same parameter types
```

Example usage:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/7649589/186943949-9a7be39e-f70b-46fd-9790-42f2969d7279.png">

The nuget packages installed in this project in case it matters
```
  <ItemGroup>
    <PackageReference Include="ByteSize" Version="2.1.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.0.0" />
    <PackageReference Include="ComputeSharp" Version="2.0.0-alpha.26" />
    <PackageReference Include="Humanizer.Core" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.cs" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.da" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.de" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.es" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.fr" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.he" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.hr" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.hu" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.it" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.ja" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.ko-KR" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.nl" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.pl" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.pt" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.ru" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.sv" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.tr" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.uk" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.zh-cn" Version="2.14.1" />
    <PackageReference Include="JeniusApps.Common" Version="0.0.2-preview" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="4.5.1" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="4.5.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="5.0.17" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="Microsoft.Toolkit" Version="7.1.2" />
    <PackageReference Include="Microsoft.Toolkit.Diagnostics" Version="7.1.2" />
    <PackageReference Include="Microsoft.Toolkit.Mvvm" Version="7.1.2" />
    <PackageReference Include="MimeTypeMapOfficial" Version="1.0.17" />
    <PackageReference Include="System.Text.Json" Version="5.0.2" />
  </ItemGroup>
```

**Comment by Sergio0694** [comment] 2022-08-26 15:52
@dpaulino Look at your output:

```
1>C:\Users\kid_j\source\repos\ambie\src\AmbientSounds\Microsoft.Toolkit.Mvvm.SourceGenerators\Microsoft.Toolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullAttribute.cs(15,27,15,43): error CS0101: The namespace 'System.Diagnostics.CodeAnalysis' already contains a definition for 'NotNullAttribute'
```

Keyword there being **Microsoft.Toolkit.Mvvm**. Are you using an outdated and not supported version? 🙃

**Comment by dpaulino** [comment] 2022-08-26 15:53
ah right, I keep forgetting the namespace changed (why is that again?). Does this mean that I cannot slowly move over from the old package to the new package? I have to update everything at once?

**Comment by Sergio0694** [comment] 2022-08-26 15:54
The namespace and package name change is because of reasons, let's not get into that now 😄

> "Does this mean that I cannot slowly move over from the old package to the new package?"

Correct, you need to migrate the whole MVVM Toolkit to the new one. It should pretty much just be a find + replace all to update the namespace though, the breaking changes are minimal. See our changelog too if you have issues, or ping me on Discord if you have any questions 🙂

**Comment by eduardoagr** [comment] 2022-08-26 16:34
@Sergio0694 What is your discord

**Comment by Sergio0694** [comment] 2022-08-26 17:23
This would be in the [UWP Community Discord server](https://discord.com/invite/uwp) 🙂

**Comment by gazle** [comment] 2022-09-22 15:34
I'm not getting these errors any more in VS Version 17.4.0 Preview 2.1 and CommunityToolkit.Mvvm version 8.0.0.

**Comment by Sergio0694** [comment] 2022-09-22 15:41
Yeah, pretty sure this is a duplicate of #343, which is now fixed 🙂

**Closed by Sergio0694** 2022-09-22 15:41 UTC
Labels: bug :bug:, external :arrow_heading_up:, mvvm-toolkit :toolbox:
