### ISSUE TITLE
Bug ObservableProperty and DataTemplate

### ISSUE THREAD

**Issue by Dotnetstore** [CommunityToolkit/dotnet#427] opened 2022-09-07 21:51 UTC
I do my navigation using DataTemplate:

`<DataTemplate DataType="{x:Type containers:MainContainerViewModel}">
    <views:MainContainerView />
</DataTemplate>`

When I use ObservableProperty I get 67 errors in build.

`[ObservableProperty]
private bool _isOpen;`

Among the errors are:
![image](https://user-images.githubusercontent.com/46750749/188989844-ba6023be-9d55-46fd-b9c8-9af25e5bca35.png)

**Comment by Sergio0694** [comment] 2022-09-07 21:57
Duplicate of #343.

**Closed by Sergio0694** 2022-09-07 21:57 UTC
