### ISSUE TITLE
AllowConcurrentExecutions=false does not stop concurrent executions

### ISSUE THREAD

**Issue by HobDev** [CommunityToolkit/dotnet#333] opened 2022-07-01 16:15 UTC
I am using this line of code as a method attribute.
```
[RelayCommand(CanExecute = nameof(CanLoginExecute), AllowConcurrentExecutions = false)]
  private async Task Login()
        {


        }
```
But when I click on Login Button multiple times the method executes multiple times. The UI code is
  `new Button{Text="LOGIN", WidthRequest=200, CornerRadius=20}.BindCommand(nameof(viewModel.LoginCommand)),`

**Comment by Sergio0694** [comment] 2022-07-01 16:21
Please don't discard the contents of the issue template - there is a reason why we set them up 🙂

> "But when I click on Login Button multiple times the method executes multiple times"

I'm not sure I understand the issue here. Is your `Login` method empty? What behavior were you expecting? If the method is empty it means the command completes immediately, so the fact you can invoke it again is by design. `AllowConcurrentExecutions = false` just means that, as the name suggests, you can't have the same command running multiple times _concurrently_. It doesn't mean you can't execute it again _after_ it completes.

Can you elaborate on what issue you think is there? Thanks!

**Comment by HobDev** [comment] 2022-07-01 16:28
Hi @Sergio0694  Thank you for the comment. I want the app behaviour such that if user clicks login button multiple times the command should cancel the execution while the command is running. In other words the button behave as disabled button until command is running. 
I am putting a break point on the start of the Login method. If I click 3 times on login button all clicks remain in the queue and run one after the another. I want the execute to be cancelled as happen with disabled button and only allow the command to be executable after the command is finish running.

**Comment by Sergio0694** [comment] 2022-07-01 16:35
> "I want the app behaviour such that if user clicks login button multiple times the command should cancel the execution while the command is running"

I assume you don't mean "cancel" as in "cancelling the previous execution" (since you have no cancellation token), but just showing the button as disabled until the execution completes, disallowing concurrent invocations. That is already the default behavior - in fact you don't even need to set `AllowConcurrentExecutions = false` at all.

I suspect you might be seeing an issue here due to how you implemented `Login`. As a test, can you just do eg. `await Task.Delay(5000)` inside `Login`, and nothing else? That should make the button be disabled for 5 seconds, and then show up as enabled again. If that is not the case, then something's wrong, but I suspect not in the MVVM Toolkit 🤔

**Comment by HobDev** [comment] 2022-07-01 16:55
Yes `await Task.Delay(5000)` disable the button. But the button is only disabled with `await`. If I write the following code it does not disable the button although it is taking about 7 seconds to reach the line `break;` on my computer.

```
int count = 1;
            for (int i = 0; i < count; i++)
            {
                string name = "parmjit";
                string fullname = $"{name} singh";
                count++;
                if (count == 10000000)
                    break;
            }
```
The button should be disabled until the command is finish execution either await or not.

**Comment by Sergio0694** [comment] 2022-07-01 17:00
That is not how it works. The code in your example is just blocking the thread, which you shouldn't be doing. The button being disabled wouldn't even matter anyway in that case - if you block the UI thread for 7 seconds it means you would literally not be able to even click on the button anyway, as the whole app would be frozen. The contract of `[RelayCommand]` and concurrent operations is pretty simple: the button is disabled while the `Task` is running, that's it. If in your original example the button wasn't being disabled, it means that your `Login` method was doing some operation without awaiting, in which case the command would just not be able to track that. You should structure your code so that it'd behave just like with the `Task.Delay` example. Closing this as by design as there is not an issue with `[RelayCommand]` as far as I can tell.

**Closed by Sergio0694** 2022-07-01 17:00 UTC
Labels: need more info :pushpin:, mvvm-toolkit :toolbox:

**Comment by HobDev** [comment] 2022-07-01 17:05
Thank you for the information.
