### ISSUE TITLE
Add Specified Property Name Overload to ObservableProperty Attribute

### ISSUE THREAD

**Issue by blueshift777** [CommunityToolkit/dotnet#835] opened 2024-01-06 00:14 UTC
This is my proposed pull-request submission: Update the ObservableProperty attribute by adding an overload that allows the user to specify the property name that is generated from the private member variable.

Change to ObservablePropertyAttribute.cs:

```
    /// <summary>
    /// Constructor with specified property name
    /// </summary>
    /// <param name="specifiedPropertyName">Specified auto-generated property name</param>
    public ObservablePropertyAttribute(string specifiedPropertyName)
    {
        SpecifiedPropertyName = specifiedPropertyName;
    }

    /// <summary>
    /// Specified auto-generated property name
    /// </summary>
    public string SpecifiedPropertyName { get; private set; } = string.Empty;

```
Example of changes to ObservablePropertyGenerator.Execute.cs:

```
            string propertyName = fieldSymbol.Name;
            if (fieldSymbol?.GetAttributes().Any() == true)
            {
                ImmutableArray<AttributeData> attributeDataSet = fieldSymbol.GetAttributes();
                AttributeData? firstAttributeData = attributeDataSet.FirstOrDefault();
                if (firstAttributeData != null)
                {
                    ImmutableArray<TypedConstant> constructorArguments = firstAttributeData.ConstructorArguments;
                    if (constructorArguments.Any() == true)
                    {
                        TypedConstant? firstConstructorArgument = constructorArguments.FirstOrDefault();
                        if (firstConstructorArgument.HasValue)
                        {
                            string specifiedPropertyName = firstConstructorArgument.Value.Value!.ToString();
                            return specifiedPropertyName;
                        }
                    }
                }
            }

            string? propertyName = fieldSymbol?.Name;

```

**Comment by blueshift777** [comment] 2024-08-06 01:01
Is there additional information you need from me regarding this request? Can it receive the requested triage?

**Comment by Sergio0694** [comment] 2024-08-06 01:03
Duplicate of #706.
Superseded by #555.

**Closed by Sergio0694** 2024-08-06 01:03 UTC
Labels: needs attention :wave:, needs triage :mag:
