### ISSUE TITLE
Add option to [ObservableProperty] to specify setter accessiblity (public/internal/protected/private)

### ISSUE THREAD

**Issue by michaelpduda** [CommunityToolkit/dotnet#380] opened 2022-08-13 20:37 UTC
### Overview

In some situations, a ViewModel property might need to be visible to the View and fire `PropertyChanged` events for binding, but should only be changeable by the ViewModel class itself, so the setter should be `private` (or possibly `internal` or `protected` depending on the situation).

For example: a property whose value changes to reflect the status of a back-end process. The View should be able to bind to this property and get the value to reflect the status in the UI, but it should not be able to change the value.

Proposal: to add a property to the `ObservableProperty` attribute that determines the accessibility of the setter on the generated property. This should be optional, and the default value should be `public` to ensure this isn't a breaking change.

### API breakdown

[/CommunityToolkit.Mvvm/ComponentModel/Attributes/ObservablePropertyAttribute.cs](https://github.com/CommunityToolkit/dotnet/blob/96517eace88d95ec52a881e3e1ed74ea51436b40/CommunityToolkit.Mvvm/ComponentModel/Attributes/ObservablePropertyAttribute.cs)
```csharp
// This enum should probably be in its own file
public enum ObservablePropertySetterAccessibility { Public, Internal, Protected, Private }

[AttributeUsage(AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
public sealed class ObservablePropertyAttribute : Attribute
{
    // New property for defining accessibility
    public ObservablePropertySetterAccessibility SetterAccessibility { get; init; } = ObservablePropertySetterAccessibility.Public;
}
```

### Usage example

```csharp
public partial class JobStatusViewModel : ObservableObject
{
    [ObservableProperty(SetterAccessibility = ObservablePropertySetterAccessibility.Private)]
    private bool _jobDone;

    [RelayCommand]
    private async Task RunJob()
    {
        JobDone = false;
        await Task.Delay(5000);
        JobDone = true;
    }
}
```

### Breaking change?

No

### Alternatives

Alternative is to manually implement such Properties with private setters that call `SetProperty`.

### Additional context

API proposal above may not be the best approach.

### Help us help you

No, just wanted to propose this

**Comment by Sergio0694** [comment] 2022-08-13 20:41
Duplicate of #291.

**Closed by Sergio0694** 2022-08-13 20:41 UTC
Labels: feature request :mailbox_with_mail:, mvvm-toolkit :toolbox:
