### ISSUE TITLE
[Mvvm] Upgrading to 8.0.0.Preview4 Breaks ICommand Attribute for me

### ISSUE THREAD

**Issue by dgerding** [CommunityToolkit/dotnet#318] opened 2022-06-16 19:34 UTC
### Describe the bug

Upgrading from 8.0.0.Preview3 to 8.0.0.Preview4 introduces compile-time error for all methods labeled with [ICommand] attribute. Reverting to 8.0.0.Preview3 restores [ICommand] code gen / functionality.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ICommandAttribute' could not be found (are you missing a using directive or an assembly reference?)
```

### Regression

8.0.0.Preview3

### Steps to reproduce

```text
Upgrading CommunityToolKit.MVVM nuget from 8.0.0.Preview3 to 8.0.0.Preview4 introduces compile-time error for all methods labeled with [ICommand] attribute. Reverting to 8.0.0.Preview3 restores [ICommand] code gen / functionality.
```

### Expected behavior

Builds and runs, including generated event handling for Command wireup.

### Screenshots

![image](https://user-images.githubusercontent.com/523279/174150145-1ebd0f98-edce-466d-a21b-1d214aca1b1c.png)

### IDE and version

VS 2022 Preview

### IDE version

Version 17.3.0 Preview 2.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0-preview4

### Help us help you

No, just wanted to report this

**Comment by dgerding** [comment] 2022-06-16 19:37
Hmmm... looks like I might not have gotten a change name or should be using RelayCommand attribute? Will report back if I fix.

**Comment by Sergio0694** [comment] 2022-06-16 22:07
Duplicate of #311

**Closed by Sergio0694** 2022-06-16 22:07 UTC
Labels: bug :bug:
