### ISSUE TITLE
[ObservablePropertyAttribute] add modifiers for generated code

### ISSUE THREAD

**Issue by Palatis** [CommunityToolkit/dotnet#814] opened 2023-12-22 21:12 UTC
### Overview

currently all property code generated by the analyzer are with no access modifiers, for example:
```csharp
[ObservableProperty]
private bool value;
```
generates
```csharp
public bool Value {
    get => value;
    set { ... }
}
```
but sometimes we might want an observable property with a little more privacy...
for example, some property that can only be modified by the class itself:
```csharp
public bool Value {
    get => value;
    private set { ... } // or protected, internal... etc.
}
```

### API breakdown

```csharp
[Flags]
public enum AccessModifier
{
    None = 0x00,
    Public = 0x01,
    Protected = 0x02,
    Internal = 0x04,
    Private = 0x08,
    ProtectedInternal = Protected | Internal,
    PrivateProtected = Private | Protected,
}

[AttributeUsage(AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
public sealed class ObservablePropertyAttribute : Attribute
{
    public AccessModifier PropertyModifier { get; }
    public AccessModifier GetModifer { get; }
    public AccessModifier SetModifier { get; }

    public ObservablePropertyAttribute() :
        this(AccessModifier.None, AccessModifier.None, AccessModifier.None)
    { }

    public ObservablePropertyAttribute(AccessModifier setModifier) :
        this(AccessModifier.None, setModifier)
    { }

    public ObservablePropertyAttribute(AccessModifier getModifier, AccessModifier setModifier) :
        this(AccessModifier.None, getModifier, setModifier)
    { }

    public ObservablePropertyAttribute(
        AccessModifier propertyModifier,
        AccessModifier getModifier,
        AccessModifier setModifier
    )
    {
        PropertyModifier = propertyModifier;
        GetModifier = getModifier;
        SetModifier = setModifier;
    }
}
```

### Usage example

```csharp
[ObservableProperty]
private bool value1;
[ObservableProperty(AccessModifier.Private)]
private bool value2;
[ObservableProperty(AccessModifier.Protected, AccessModifier.None, AccessModifier.Internal)]
private bool value3;
```
now generates
```csharp
public bool Value1 { get => value1; set => { ... } }
public bool Value2 { get => value2; private set => { ... } }
protected bool Value3 { get => value3; internal set => { ... } }
```

### Breaking change?

No

### Alternatives

none, I just manually code the property instead of using `ObservablePropertyAttribute`.

### Additional context

none

### Help us help you

Yes, but only if others can assist

**Comment by Palatis** [comment] 2023-12-22 21:30
another reason for this is that we can use `NotifyPropertyChangedFor` and such on the generated property.

**Comment by Sergio0694** [comment] 2023-12-22 21:35
Duplicate of #291.
Superseded by #555.

**Closed by Sergio0694** 2023-12-22 21:35 UTC
Labels: feature request :mailbox_with_mail:

**Comment by Palatis** [comment] 2023-12-24 17:11
okay, then.
