### ISSUE TITLE
MVVM Toolkit Errors

### ISSUE THREAD

**Issue by QJS-RH** [CommunityToolkit/dotnet#625] opened 2023-03-01 02:56 UTC
### Discussed in https://github.com/CommunityToolkit/dotnet/discussions/624

<div type='discussions-op-text'>

<sup>Originally posted by **QJS-RH** March  1, 2023</sup>
VS 2022 17.5.0
Create WPF Application and add Nuget package CommunityToolkit.Mvvm 8.1.0

Immediately analyzers show errors MVVMTK0008 with an X, 0020 with an X, 0032 with Info, 0033 with Info and 0034 with Info.
Code compiles and runs.

![MVVMErrors](https://user-images.githubusercontent.com/10412049/222031134-b17aed6f-777c-43d7-b5bb-877448b68ab4.JPG)

As I program more, more errors appear  Generally CS0103

Adding a simple class as

`using CommunityToolkit.Mvvm.ComponentModel;

namespace RHOKSWPF_Working;

public partial class MainProgressBarVM : ObservableObject
{
    private readonly string ProgressMessage = "Loading Application";

    public MainProgressBarVM()
    {
        ThisIsMyVariable = ProgressMessage;
    }

    [ObservableProperty] private string? thisIsMyVariable;
}
`

Produces Error CS0103

![Capture](https://user-images.githubusercontent.com/10412049/222032967-58613719-e66e-4b5c-801f-75fc4c688b3a.JPG)

csproj file for reference.

![image](https://user-images.githubusercontent.com/10412049/222033341-93a9abbb-f0d2-4fe9-973f-6f3507e88fe8.png)
</div>

**Comment by amdo1148** [comment] 2023-03-14 03:55
I had the same issue. Is there any update for this error and when it will be the next update? Thank you!

**Comment by Sergio0694** [comment] 2023-03-25 01:44
That red squiggly line is an issue with IntelliSense, closing as a duplicate of #493.

**Closed by Sergio0694** 2023-03-25 01:44 UTC
Labels: external :arrow_heading_up:, mvvm-toolkit :toolbox:
