### ISSUE TITLE
WinRT.Runtime not found Error?

### ISSUE THREAD

**Issue by depute** [CommunityToolkit/dotnet#933] opened 2024-08-31 15:49 UTC
### Describe the bug

![image](https://github.com/user-attachments/assets/12343a5f-d964-4de0-866f-7b1f898acdec)
Error loaction : App.xaml.cs OnStartup

### Regression

8.2.2

### Steps to reproduce

```text
1. CommunityToolkit.Mvvm 8.2.2 use and build success
2. Run Success
3. CommunityToolkit.Mvvm 8.3.0 update and build success
4. Run Error(Screenshot)
```

### Expected behavior

Build and run success

### IDE and version

VS 2022

### IDE version

17.11.2

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.3.0

### Additional context

This project created by Template Studio for WPF
.NET 8 target

### Help us help you

No, just wanted to report this

**Comment by JORGEGO** [comment] 2024-08-31 16:49
Same for me, back to previous version

**Comment by Sergio0694** [comment] 2024-08-31 17:11
Duplicate of #923, the workaround is in https://github.com/CommunityToolkit/dotnet/issues/923#issuecomment-2314444048 🙂

**Closed by Sergio0694** 2024-08-31 17:11 UTC
Labels: bug :bug:
