### ISSUE TITLE
Using CommunityToolkit.Mvvm in WinUI .NET8 App warns different WinRT versions

### ISSUE THREAD

**Issue by afluegge** [CommunityToolkit/dotnet#934] opened 2024-08-31 17:27 UTC
### Describe the bug

I try to use CommunityToolkit.Mvvm in a WinUI App using .NET8.  The compile warning I get is the following:

```
    Warning MSB3277: Found conflicts between different versions of "WinRT.Runtime" that could not be resolved.
There was a conflict between "WinRT.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" and "WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709".
    "WinRT.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" was chosen because it was primary and "WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" was not.
    References which depend on "WinRT.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" [D:\packages\NuGet\cache\microsoft.windows.sdk.net.ref\10.0.19041.34\lib\net6.0\WinRT.Runtime.dll].
        D:\packages\NuGet\cache\microsoft.windows.sdk.net.ref\10.0.19041.34\lib\net6.0\WinRT.Runtime.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\microsoft.windows.sdk.net.ref\10.0.19041.34\lib\net6.0\WinRT.Runtime.dll".
            D:\packages\NuGet\cache\microsoft.windows.sdk.net.ref\10.0.19041.34\lib/net6.0/WinRT.Runtime.dll
    References which depend on or have been unified to "WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" [].
        D:\Development\Projects\HaislManager\HaislManager.Controls\bin\Debug\net8.0-windows10.0.19041.0\HaislManager.Controls.dll
          Project file item includes which caused reference "D:\Development\Projects\HaislManager\HaislManager.Controls\bin\Debug\net8.0-windows10.0.19041.0\HaislManager.Controls.dll".
            D:\Development\Projects\HaislManager\HaislManager.Controls\bin\Debug\net8.0-windows10.0.19041.0\HaislManager.Controls.dll
        D:\packages\NuGet\cache\communitytoolkit.mvvm\8.3.0\lib\net8.0-windows10.0.17763\CommunityToolkit.Mvvm.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\communitytoolkit.mvvm\8.3.0\lib\net8.0-windows10.0.17763\CommunityToolkit.Mvvm.dll".
            D:\packages\NuGet\cache\communitytoolkit.mvvm\8.3.0\lib\net8.0-windows10.0.17763\CommunityToolkit.Mvvm.dll
        D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.InteractiveExperiences.Projection.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.InteractiveExperiences.Projection.dll".
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.InteractiveExperiences.Projection.dll
            D:\Development\Projects\HaislManager\HaislManager.Controls\bin\Debug\net8.0-windows10.0.19041.0\HaislManager.Controls.dll
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI.dll
            D:\packages\NuGet\cache\microsoft.xaml.behaviors.winui.managed\2.0.9\lib\net5.0-windows10.0.17763.0\Microsoft.Xaml.Interactions.dll
            D:\packages\NuGet\cache\microsoft.xaml.behaviors.winui.managed\2.0.9\lib\net5.0-windows10.0.17763.0\Microsoft.Xaml.Interactivity.dll
            D:\packages\NuGet\cache\winuiex\2.3.4\lib\net6.0-windows10.0.18362\WinUIEx.dll
        D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI.dll".
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI.dll
            D:\Development\Projects\HaislManager\HaislManager.Controls\bin\Debug\net8.0-windows10.0.19041.0\HaislManager.Controls.dll
            D:\packages\NuGet\cache\microsoft.xaml.behaviors.winui.managed\2.0.9\lib\net5.0-windows10.0.17763.0\Microsoft.Xaml.Interactions.dll
            D:\packages\NuGet\cache\microsoft.xaml.behaviors.winui.managed\2.0.9\lib\net5.0-windows10.0.17763.0\Microsoft.Xaml.Interactivity.dll
            D:\packages\NuGet\cache\winuiex\2.3.4\lib\net6.0-windows10.0.18362\WinUIEx.dll
        D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppLifecycle.Projection.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppLifecycle.Projection.dll".
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppLifecycle.Projection.dll
        D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Builder.Projection.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Builder.Projection.dll".
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Builder.Projection.dll
        D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Projection.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Projection.dll".
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Projection.dll
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Builder.Projection.dll
        D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.dll".
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.dll
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Management.Deployment.Projection.dll
        D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.Resources.Projection.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.Resources.Projection.dll".
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.Resources.Projection.dll
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI.dll
            D:\Development\Projects\HaislManager\HaislManager.Controls\bin\Debug\net8.0-windows10.0.19041.0\HaislManager.Controls.dll
            D:\packages\NuGet\cache\microsoft.xaml.behaviors.winui.managed\2.0.9\lib\net5.0-windows10.0.17763.0\Microsoft.Xaml.Interactions.dll
            D:\packages\NuGet\cache\microsoft.xaml.behaviors.winui.managed\2.0.9\lib\net5.0-windows10.0.17763.0\Microsoft.Xaml.Interactivity.dll
            D:\packages\NuGet\cache\winuiex\2.3.4\lib\net6.0-windows10.0.18362\WinUIEx.dll
        D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll".
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll
        D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Management.Deployment.Projection.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Management.Deployment.Projection.dll".
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Management.Deployment.Projection.dll
        D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.PushNotifications.Projection.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.PushNotifications.Projection.dll".
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.PushNotifications.Projection.dll
        D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Security.AccessControl.Projection.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Security.AccessControl.Projection.dll".
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Security.AccessControl.Projection.dll
        D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Power.Projection.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Power.Projection.dll".
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Power.Projection.dll
        D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Projection.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Projection.dll".
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Projection.dll
        D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Widgets.Projection.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Widgets.Projection.dll".
            D:\packages\NuGet\cache\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Widgets.Projection.dll
        D:\packages\NuGet\cache\winuiex\2.3.4\lib\net6.0-windows10.0.18362\WinUIEx.dll
          Project file item includes which caused reference "D:\packages\NuGet\cache\winuiex\2.3.4\lib\net6.0-windows10.0.18362\WinUIEx.dll".
            D:\packages\NuGet\cache\winuiex\2.3.4\lib\net6.0-windows10.0.18362\WinUIEx.dll (2413, 6)
```

### Steps to reproduce

```text
- Use the "Blank App" template for WinUI in Visual Studio 2022 to create a new WinUI app thatuses .NET8
- Compile the app.  No warnings.
- Add nuget package "CommunityToolkit.Mvvm" with version 8.3.0
- Compile the app and you can see the compiler warning.
```

### Expected behavior

No such compiler warning.

### IDE and version

VS 2022

### IDE version

Microsoft Visual Studio Community 2022 Version 17.11.2

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.3.0

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment] 2024-08-31 17:46
Duplicate of #923, the workaround is in https://github.com/CommunityToolkit/dotnet/issues/923#issuecomment-2314444048 🙂

**Closed by Sergio0694** 2024-08-31 17:46 UTC
Labels: bug :bug:
