### ISSUE TITLE
SourceGenerator sometimes will cause compilation failed

### ISSUE THREAD

**Issue by laolarou726** [CommunityToolkit/dotnet#584] opened 2023-01-25 00:40 UTC
### Describe the bug

SourceGenerator sometimes will cause VS to fail to build the project. VS will not show any errors in the list but will show errors in the output window:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/25716486/214453498-17beb433-6ba3-47fb-ad63-cec076965f06.png">

error CS0759: No definition declaration found for implementation declaration of partial method 'UIManager.OnSelectedBgFillColorChanged(SolidColorBrush?)'

### Regression

810

### Steps to reproduce

Actually, this bug seems randomly happened on my project. 
Every time my solution is to reboot the computer and reopen Visual Studio. 
If I use **dotnet build** to build the project, no errors will show and I'll get the compiled binary.

### Expected behavior

The project should be compiled without any errors.

### IDE and version

VS 2022

### IDE version

17.4.3

### Nuget packages

- [X] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.1.0

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by sej69** [comment] 2023-02-02 17:48
I am having this EXACT issue, too.  It will just blow up while editing the code on another viewmodel which is open but not being edited.  I didn't experience this issue until just a few days ago and now it's happening all the time to me.  I'm having to exit and reopen a few times / hour.

I think in correlation to this issue, I'm experiencing an ObservableProperty issue which I think is related to this.  You can see the open question here on SO: https://stackoverflow.com/questions/75326732/viewmodels-observablecollection-and-observableproperty-is-throwing-a-null-refer

**Comment by sej69** [comment] 2023-02-02 17:54
I should say I can also duplicate this issue in the ViewModel by commenting out an observable property, wait a moment to get the compiler to throw some errors, then uncomment it.  The net result is then all ObservableProperty variables defined in code will go into this:

![image](https://user-images.githubusercontent.com/16020949/216403428-b49786a5-00a9-4689-8a5e-0f0711e5ed8e.png)

If I exit VS and go back into it, these errors will go away.

**Comment by RokG** [comment] 2023-02-02 18:19
I'm having a similiar issue, only that everything works...
I'm getting a bunch of "The name '<itemname>' does not exist in current context" in the Error List and res squigly lines, however everything compiles and works fine. 
Can't seem to find the reason for this.. 

Used to have to reopen VS to make it go away but now I found out that just reloading a project works also.
Most commonly this happens on properties with these two attributes together:
`
        [ObservableProperty]
        [NotifyCanExecuteChangedFor(nameof(CreateCardDesignCommand))]
`
But over time, more and more `[ObservableProperty]` fields get marked as non-existing (In the same .cs file).. Looking in the autogenerated code I can see that the property really is not there.

**Comment by sej69** [comment] 2023-02-02 19:05
Confirmed, the same for me.  If I unload / reload the project it comes back, too.

I have the same issue if I hover over a variable where it says "[variable] does not exist in the current context".

I went through my other viewmodels and tried the same drill and every one of the them did the same thing as I mentioned.

In playing with this, I went to my most complex VM that I was working with prior on this issue and when I commented out a ObservableProperty variable then uncommented it back in again after seeing the expected error, only one other ObservableProperty variable came up with this issue.  The last few times it was all of them (except for the one that was commented out).

Where are you seeing the autogenerated code?

**Comment by RokG** [comment] 2023-02-03 20:25
It seems to allways start with `[NotifyCanExecuteChangedFor(nameof(SomeMethod))]` attributes..
The methods in them are allways the first one to be labeled as Errors, then from there, other properties slowly get labeled too.

Didn't really find any pattern yet. My project is still in heavy development so I'm constantly adding views, models, viewmodels...

Fastest way I found to temporarily resolve this is to just unload/reload project or switching to another repo and back.
It is mostly bothering me because I can't use hot-reload since there are these "errors"..
Or in case of actual errors, they are hidden among these fake ones..

It's interesting how everything compiles regardless and works perfectly fine... maybe VS IDE just points to the wrong auto-generated file?

I can see the autogenerated code by pressing F12 on any of the properties that are not affected by this bug, which opens a file in VisualStudio and from there I can right-click on file tab and choose Open file location.
For me, this files are in C:\Users\<myUserName>\AppData\Local\Temp\VSGeneratedDocuments\<somegibberishfolder>

I'm still on .net5 :)
It's an older project that I've refactored to use this toolkit, might update just in case.. didn't think of doing that yet.

**Comment by sej69** [comment] 2023-02-03 20:27
Ok, I was wondering if it was .net 6 to .net 7 which is what I did with this project. I'm in the process of recreating the project in a native .net 7 app.  Btw, going from 6 to 7 was very painful...

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by faheys** [comment] 2023-02-09 01:22
I've encountered this issue with version 8.1.0. Rolling back the package to version 8.0.0 fixed the issue for me.

**Comment by dpaulino** [comment] 2023-02-11 05:29
Started getting this issue with 8.1.0 as well

**Comment by sej69** [comment] 2023-02-16 16:30
Confirmed, going back to 8.0.0 resolved it, thanks faheys.

**Comment by sdunc** [comment] 2023-02-24 22:22
Could not build a fresh project with 8.1.0. Returning to 8.0 fixed for me as well.

**Comment by RokG** [comment] 2023-02-25 01:15
Same, reverting to 8.0.0 fixed this issue

**Comment by Sergio0694** [comment] 2023-03-25 01:49
Closing as duplicate of #493, let's just use that one for tracking.
This is also tracked in Roslyn by https://github.com/dotnet/roslyn/issues/67123.

**Closed by Sergio0694** 2023-03-25 01:49 UTC
Labels: external :arrow_heading_up:, mvvm-toolkit :toolbox:
