### ISSUE TITLE
ObservableColletion and ObservableObject

### ISSUE THREAD

**Issue by candinho1987** [CommunityToolkit/dotnet#506] opened 2022-11-18 23:49 UTC
### Discussed in https://github.com/CommunityToolkit/dotnet/discussions/504

<div type='discussions-op-text'>

<sup>Originally posted by **candinho1987** November 16, 2022</sup>
Hello everyone, i'n trying to use observable object and collection, but the ui doesn't get updated,
```csharp
public partial class MedidasViewModel : ObservableObject
{
    public ObservableCollection<Medida> Medidas { get; set; }    

    public MedidasViewModel()
    {
        Medidas = new ObservableCollection<Medida>();
        
        using (AppDbContext context = new AppDbContext())
        {
            
            List<Medida> lista = context.Medida.ToList();


            foreach (var item in lista)
            {
                Medidas.Add(item);
                
            }
        }
    }

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(DescricaoNovaMedida))]
    string descricaoNova;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(SiglaNovaMedida))]
    string siglaNova;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(ConvervorNovaMedida))]
    decimal conversorNova;
    public string DescricaoNovaMedida => descricaoNova;
    public string SiglaNovaMedida => siglaNova;
    public double ConvervorNovaMedida => Convert.ToDouble(conversorNova);

    [RelayCommand]
    void SalvarNovaMedidaVM()
    {

        Medida medida = new Medida();
        medida.Descricao = DescricaoNovaMedida;
        medida.Sigla = SiglaNovaMedida;
        medida.Conversor = Convert.ToDecimal(ConvervorNovaMedida);
        using (var context = new AppDbContext())
        {
            context.Medida.Add(medida);
            context.SaveChanges();
            int idNovaMedida = medida.Id;
            Medidas.Add(medida);
        }
    }
}
```
When i execute `Medidas.Add(medida);` the collection get the new Medida record, but the ui is not updated with the newly added medida, and if i close the page and open again, then the new medida show up on the picker/datagrid.
What do i need to implement to make my observablecollection realy observable?</div>

**Comment by michael-hawker** [comment] 2022-12-06 02:14
This is just a duplicate of the discussion. Discussions is the proper place to ask questions. Hopefully someone can chime in on the issue. At first glance, I don't see anything wrong.

More details about what framework you're using, how you're binding to it, what you've inspected and see in the debugger at certain points would be helpful for folks to know there in order to help you more.

**Closed by michael-hawker** 2022-12-06 02:14 UTC
