### ISSUE TITLE
Compilation Error on .NET Framework

### ISSUE THREAD

**Issue by xmine64** [CommunityToolkit/dotnet#495] opened 2022-11-10 18:44 UTC
### Describe the bug

When using .NET Framework 4.8 project build fails with the following errors:
<details>
<summary>Errors Log</summary>
...\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullAttribute.g.cs(12,27): error CS0101: The namespace 'System.Diagnostics.CodeAnalysis' already contains a definition for 'NotNullAttribute'

...\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute.g.cs(11,27): error CS0101: The namespace 'System.Diagnostics.CodeAnalysis' already contains a definition for 'NotNullIfNotNullAttribute'

...\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute.g.cs(10,6): error CS0579: Duplicate 'AttributeUsage' attribute

...\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullAttribute.g.cs(11,6): error CS0579: Duplicate 'AttributeUsage' attribute

...\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute.g.cs(17,16): error CS0111: Type 'NotNullIfNotNullAttribute' already defines a member called 'NotNullIfNotNullAttribute' with the same parameter types
</details>

Everything is fine when using .NET 6, I guess the code generator is not compatible with .NET Framework when I have `<Nullable>enable</Nullable>` and `<LangVersion>9</LangVersion>` but not sure, needs to be tested.

### Steps to reproduce

```text
1. Create a .NET Framework 4.8 project with `<Nullable>enable</Nullable>` and `<LangVersion>9</LangVersion>`.
2. Add CommunityToolkit.Mvvm 8.0.0 NuGet package
3. Try to build it.
```

### Expected behavior

The app should get built without any problem.

### IDE and version

VS 2022

### IDE version

17.3.1

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Help us help you

No, just wanted to report this

**Comment by hawkerm** [comment] 2022-12-10 11:20
Hmm, I think I hit this same thing with 8.1-preview1, the error messages are basically the same:

```
2>I:\code\...\...\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullAttribute.g.cs(12,27,12,43): error CS0101: The namespace 'System.Diagnostics.CodeAnalysis' already contains a definition for 'NotNullAttribute'
2>I:\code\...\...\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute.g.cs(11,27,11,52): error CS0101: The namespace 'System.Diagnostics.CodeAnalysis' already contains a definition for 'NotNullIfNotNullAttribute'
2>I:\code\...\...\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullAttribute.g.cs(11,6,11,20): error CS0579: Duplicate 'AttributeUsage' attribute
2>I:\code\...\...\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute.g.cs(10,6,10,20): error CS0579: Duplicate 'AttributeUsage' attribute
2>I:\code\...\...\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.NullabilityAttributesGenerator\System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute.g.cs(17,16,17,41): error CS0111: Type 'NotNullIfNotNullAttribute' already defines a member called 'NotNullIfNotNullAttribute' with the same parameter types
```

But I have a .NET Standard 2.0 class library with language set to `latest`.  That project seems to build. But it's the UWP app it's being referenced in that throws these errors...

**Comment by hawkerm** [comment] 2022-12-10 11:50
Attaching a minimum repro here:

[MvvmMinRepoNullAttribute.zip](https://github.com/CommunityToolkit/dotnet/files/10199999/MvvmMinRepoNullAttribute.zip)

I just:

1. Created a UWP project
2. Created a .NET Standard library
3. Added MVVM Toolkit 8.1-preview1 to library project
4. Referenced library project in UWP head
5. Build

If I downgrade to 8.0 it worked in my other project. So even though errors are the same, this may be different root cause compared to the OP of this issue.

**Comment by Sergio0694** [comment] 2022-12-17 16:26
Thanks for the report! This is the same issue as #540, should be fixed by #541 🙂

**Closed** 2022-12-17 16:26 UTC
Labels: bug :bug:, duplicate :busts_in_silhouette:, mvvm-toolkit :toolbox:

**Comment by xmine64** [comment] 2022-12-19 11:34
Well I was using SDK-style project, not legacy. But I'll reopen it if I can reproduce it again.

**Comment by Sergio0694** [comment] 2022-12-19 15:31
Oh. Mmmh this seems like one of those issues with the generators running twice again, which should be fixed in the new WPF SDK. Feel free to let me know if you can repro again! Also, #538 should potentially help with this at least a bit 🤔
