### ISSUE TITLE
Add abilities to control the access level of generated [ObservableProperty] attribute 

### ISSUE THREAD

**Issue by laolarou726** [CommunityToolkit/dotnet#585] opened 2023-01-25 01:16 UTC
### Overview

Currently CommunityToolkit can only generate ObservableProperties with both public getter and setter. Sometimes we need the property be private or the setter be private. Maybe we can have multiple attributes like [Readonly] to change the behavior of the generation.

### API breakdown

[ObservableProperty]
[Readonly]
private int _counter; // generate property with {get;}

[ObservableProperty]
[PrivateSet]
private string _text; // generate property with {get; private set;}

### Usage example

Same as previous one

### Breaking change?

No

### Alternatives

Maybe trying to use any attributes that C# already have?

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by Sergio0694** [comment] 2023-01-27 22:02
Duplicate of #555, this will be supported through that.

**Closed by Sergio0694** 2023-01-27 22:02 UTC
Labels: feature request :mailbox_with_mail:
