### ISSUE TITLE
Mismatch versions 

### ISSUE THREAD

**Issue by eduardoagr** [CommunityToolkit/dotnet#931] opened 2024-08-30 19:57 UTC
### Describe the bug

I started Maui project, and installed this plug in, because I wanted to use maps, I install the mct (To make sure it works on Window), when I started to use this to create a vm, everything worked great on Android, but for windows. It gives me this error 

`FileNotFoundException: Could not load file or assembly 'WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709'. The system cannot find the file specified. 
`

I search n bind and find

` I have found that this is typically an issue with SDK mismatching and that it is also a problem with cache. So, I suggest that you check to make sure that the SDK versions you are using match those used for .NET MAUI (where the Map control comes from) and the .NET MAUI Community Toolkit (where the Windows Map control comes from - which is 8.0.203 - which can be found in the global.json

### Steps to reproduce

```text
1. make a project in maui
2. Install this and mct.maps
3. paster this #if WINDOWS
        .UseMauiCommunityToolkitMaps("xxx")
#elif ANDROID || IOS
                .UseMauiMaps()
#endif```
4. make a vm
5. bind the map and the mapspan to the map.
6. run it on Windows
```

### Expected behavior

Display map on win

### Screenshots

![image](https://github.com/user-attachments/assets/66ff4b14-6b4b-4f49-9e46-4953762b0a5c)

### IDE and version

VS 2022

### IDE version

17

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.3

### Help us help you

No, just wanted to report this

**Comment by 4broadcast** [comment] 2024-08-30 20:13
Same thing:  type initializer exception on a WINUI 3 project, WinAppSdk 1.5. Can't find winrt version 2.1.0.0.

**Comment by Sergio0694** [comment] 2024-08-30 20:28
Duplicate of #923, the workaround is in https://github.com/CommunityToolkit/dotnet/issues/923#issuecomment-2314444048 🙂

**Closed by Sergio0694** 2024-08-30 20:28 UTC
Labels: bug :bug:
