### ISSUE TITLE
Provide IsNotBusy() method or IsNotBusy readonly property with a new attribute [DependsOnProperty(nameof(IsBusy))]

### ISSUE THREAD

**Issue by suugbut** [CommunityToolkit/dotnet#938] opened 2024-09-06 05:41 UTC
In my opinion `ObservableProperty` (as a publisher) should not know anything about `ICommand` or other properties (as a subscriber). So the following
```cs
public partial class PersonViewModel : ObservableObject
{
    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(SaveCommand))]
    [NotifyPropertyChangedFor(nameof(IsNotBusy))]
    private boo isBusy;

    [RelayCommand(CanExecute = nameof(IsNotBusy))]
    private void Save() { }
    
    private bool IsNotBusy => !IsBusy; // it can be a method too
}
```
is more elegant if it can be simplified as follows.
```cs
public partial class PersonViewModel : ObservableObject
{
    [ObservableProperty]
    private bool isBusy;

    [RelayCommand(CanExecute = nameof(IsNotBusy))]
    private void Save() { }
    
    [DependsOnProperty(nameof(IsBusy))] // <======= the requested attribute.
    private bool IsNotBusy => !IsBusy;
}
```
When `SaveCommand` depends on `IsNotBusy` that depends on `IsBusy`, it is enough to only decorate `IsNotBusy` with `DependsOnProperty(nameof(IsBusy))`.

Interestingly `DependsOnProperty`  lets `CanSave()`, for example, depend on property `IsBusy` defined in the base class  `BaseViewModel`.
```cs
public partial class BaseViewModel : ObservableObject
{
    [ObservableProperty]
    private bool isBusy;
}
public partial class PersonViewModel : BaseViewModel
{
    [ObservableProperty]
    private bool isDeleted;

    [RelayCommand(CanExecute = nameof(CanSave))]
    private void Save() { }
    
    [DependsOnProperty(nameof(IsBusy))] // <======= the requested attribute.
    [DependsOnProperty(nameof(IsDeleted))] // <======= the requested attribute.
    private bool CanSave => !IsBusy && !IsDeleted;
}
```

Any comments are welcome.

**Comment by hawkerm** [comment] 2024-09-06 08:52
Duplicate of #377 and #367.

A `[DependsOn]` was already discussed in the past, this comment touches on it here: https://github.com/CommunityToolkit/dotnet/issues/367#issuecomment-1252708138; these parts in particular are relevant:

> It'd introduce a different way to do exactly the same, which adds further confusion.
> It breaks the established pattern of generators immediately affecting annotating code, not indirectly.
> It makes the generators less efficient, as they'd now have to have extra logic to look at all annotated properties.

**Closed** 2024-09-27 20:29 UTC
Labels: feature request :mailbox_with_mail:
