### ISSUE TITLE
CS0103	The name 'Property' does not exist in the current context

### ISSUE THREAD

**Issue by Diyari-Kurdi** [CommunityToolkit/dotnet#677] opened 2023-04-29 16:40 UTC
### CS0103
After updating **CommunityToolkit.MVVM** from version **8.0.0** to **8.2.0**, I encountered errors in both **WPF .Net 7** and **WinUI .Net 7** projects. These errors only appear in the Error List in Visual Studio, and I am still able to build the project without any issues. Additionally, I should note that these errors in Visual Studio are intermittent and not consistently reproducible.

### Regression

8.0.0

### Steps to reproduce

```text
1. Create a WinUI Project (.NET 7)
2. Add CommunityToolkit.MVVM (8.0.0)
3. Add a property with the ObservableProperty attribute
4. Build the project
5. Update CommunityToolkit.MVVM to 8.2.0
```

### Expected behavior

I expect Visual Studio to not show any errors in the Error List after updating the CommunityToolkit.MVVM package, while still being able to build the project successfully.

### Screenshots

![image](https://user-images.githubusercontent.com/65598554/235308502-e11e6e41-8ed7-4486-905f-3d78b074b84f.png)

### IDE and version

VS 2022

### IDE version

17.5.4

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.2.0

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment] 2023-04-29 16:47
Duplicate of #493, which is then dependent on https://github.com/dotnet/roslyn/issues/67123.
Could you also try using VS 17.6 Preview 5 (or above)? There should be some bug fixes there that might help 🙂

**Closed by Sergio0694** 2023-04-29 16:47 UTC
Labels: duplicate :busts_in_silhouette:, external :arrow_heading_up:, mvvm-toolkit :toolbox:
