### ISSUE TITLE
ObservableProperty causes build error

### ISSUE THREAD

**Issue by mattleibow** [CommunityToolkit/dotnet#598] opened 2023-02-08 19:13 UTC
---
**Issue moved from dotnet/maui#13191**
- Please respond to @williambuchanan2.

---

_From @williambuchanan2 on Wednesday, February 8, 2023 10:33:09 AM_

### Description

When you create an observable property, and then try to access it in the code, you get a build error.

### Steps to Reproduce

1. In Visual Studio, Create observable property
2. Access it in the code
3. Build - see error.

Example code:
```C#
    [ObservableProperty]
    public string _contact1Name;
....
        Contact1Name = "Hello";
```

Error	CS0103	The name 'Contact1Mobile' does not exist in the current context xxxx (net7.0-android), xxxx (net7.0-ios)	C:\xxx\SupportContactsPageVm.cs	63	Active

![image](https://user-images.githubusercontent.com/32165641/217504787-bf7c6bd6-74d4-4b26-bd98-75136741b4f6.png)

### Link to public reproduction project repository

?

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Windows

### Affected platform versions

net7.0

### Did you find any workaround?

No

**Comment by tobiwae** [comment] 2023-02-08 20:34
I have that issue too in a .NET 7 / C# 11 Maui App with CommunityToolkit.Mvvm 8.1.0. Closing VS, deleting the bin and obj folders and restarting / rebuilding fixes the problem for some time, but then it occurs again after some time.

**Comment by Sergio0694** [comment] 2023-02-08 20:58
Those are not errors, they're just telling you what kind of diagnostics those analyzers can produce.

**Comment by rogamaral** [comment] 2023-02-09 21:31
Same issue too.

.Net 6 WPF project.
Visual Studio 17.4.4.
MVVMTK 8.1.0

![Captura de Ecrã](https://user-images.githubusercontent.com/5101967/217943080-8ebb8b25-6d65-459f-9133-2edcbe98446f.png)

Despite the compilation error, I am able to build and run the application without errors.

**Comment by Sergio0694** [comment] 2023-02-09 22:02
This all seems to just be IntelliSense related, we can't really do anything about it from our end.

cc. hey @sharwell, we're getting quite a lot of issues like this one which all just seem to be related to tooling rather than the MVVM Toolkit per se, would you have a suggestion on how we should handle these? Do we just close these and redirect authors to open issues in the Roslyn repo, or something else? It's not really clear for us how we should address these issues 😅

**Comment by Hakoyu** [comment] 2023-02-10 13:28
I also encountered the same problem, which caused a lot of confusion for the code debugging.

**Comment by Sergio0694** [comment] 2023-02-13 20:07
> "I think this still needs to be explained or those errors to be put somewhere else"

Maybe, but this is not the right place for this 🙂
You'll want to report that to the feedback tool for Visual Studio.

> "Additionally I find this new warning in my solution:"

That is completely unrelated. Please just open a separate issue/discussion for that. It's very hard for us to keep track of feedback and answer questions if people just start cross-posting in unrelated issues with other questions that are off topic 🥲

> "By the way: the shown errors are only visible after restarting visual studio."

That is a roslyn issue, I think I've seen that mentioned a few times before as well.
Consider reporting that in the Roslyn repo if there isn't an issue for that already.

**Comment by JasperCalapini** [comment] 2023-03-01 01:59
Have the same problem after I upgrad VS. I tried to reinstall CommunityToolkit and the error in the intellisense, gone.

**Comment by Hottemax** [comment] 2023-03-01 06:01
> Maybe, but this is not the right place for this 🙂
> You'll want to report that to the feedback tool for Visual Studio.

@Sergio0694 , you have built a great tool, and you have at least some kind of access since you are part of the Microsoft team.

This issue has been reported and raised repeatedly, by different people, in the Visual Studio feedback tool as well as the Roslyn repo. So far, nothing has happened, even though this has been around for quite a while now.

Through no fault of your own, the tool you guys built is adversely affected. Can you not somehow expedite this issue internally?

**Comment by Synthaxe42** [comment] 2023-03-09 21:49
[For the record] Same issue on: 

CommunityToolkit.Mvvm 8.1.0
VS 17.5.1, or
VS 17.6.0 Preview 1.0

(And yes, I've read that it's a Roslyn issue.  Cheers.)

**Comment by Sergio0694** [comment] 2023-03-25 01:48
Closing as a duplicate of #493. Also tracked by https://github.com/dotnet/roslyn/issues/67123.

**Closed by Sergio0694** 2023-03-25 01:48 UTC
Labels: external :arrow_heading_up:, mvvm-toolkit :toolbox:

**Comment by sharwell** [comment] 2023-05-05 13:18
> As quick fix for me is i run VS2022 as administrators. the issue is lesser

Note that running as administrator would have no impact on this scenario.
