### ISSUE TITLE
MVVM/WASDK1.2/WinUI3 - Not Generating Source - VS2022 - .NET 7

### ISSUE THREAD

**Issue by DJRM2021** [CommunityToolkit/dotnet#623] opened 2023-02-28 00:38 UTC
Can someone please help me?
My project is a Windows App SDK 1.2 / WinUI 3 desktop app, targeting .NET 7, which means by default, according to [this](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version), the compiler is using C# 11 as the default. I even added the ```<LangVersion>11.0</LangVersion>``` in my .csproj file but still the error is there and MVVM is not generating codes.

![image](https://user-images.githubusercontent.com/77593544/221364406-d79f66d9-473b-47ce-b10a-aa49467dd8c5.png)
![image](https://user-images.githubusercontent.com/77593544/221364430-35cefb08-4398-44a2-8da1-93011ed22641.png)

_Originally posted by @DJRM2021 in https://github.com/CommunityToolkit/dotnet/discussions/621_

**Comment by normschaeffer** [comment] 2023-03-04 16:43
I am running into a similar issue in a Maui app I am writing.

I have a BaseViewModel with a few ObservableProperties. When I create a new viewmodel and inherit the baseviewmodel, the inherited properties throw a CS0103 error (The property does not exist in the current context).

**Workaround in my case**

In my baseviewmodel,  I highlight and cut everything, leaving the class empty. Then paste it back in, save and continue my work. My Windows and Android builds work find after that.

**Comment by Sergio0694** [comment] 2023-03-25 01:47
Closing as duplicate of #493, that just seems some Solution Explorer UI issue.
You should still be able to reference those properties even if they don't show up.
If not, then it would seem Roslyn is having more problems, try going back to 8.0 temporarily, it might help.

**Closed by Sergio0694** 2023-03-25 01:47 UTC
Labels: external :arrow_heading_up:, mvvm-toolkit :toolbox:

**Comment by mscholz5** [comment] 2023-08-24 08:24
Regarding the example of the initial post:
The generated sources should be found within "Observable**Property**Generator", not "Observable**Object**Generator".
Does the build succeed in the output window? Are there errors listed by IntelliSense?
