### ISSUE TITLE
MVVM Toolkit ObservableProperty Key

### ISSUE THREAD

**Issue by QJS-RH** [CommunityToolkit/dotnet#340] opened 2022-06-30 22:55 UTC
I am looking at the new Code Generation in MVVM Toolkit.
I am attempting to create a database using Code First and EntityFrameworkCore.
If I use the Observable Validator I can generate a column as:

[ObservableProperty]
[Key]
[Required]
string m_CPY_ID;

But it does not recognise the KEY attribute.

I then have to generate any KEY attributes as :
private string m_CPY_ID;

     [Key]
     [Required]
     public string CPY_ID
     {
         get => m_CPY_ID;
         set => SetProperty(ref m_CPY_ID, value);
     }

Is it possible to have the ObservableProperty and autogenerate the code and have a KEY value?

Regards

**Comment by michael-hawker** [comment] 2022-07-07 18:40
Think this is a duplicate of #208. Only data validation properties are forwarded by the source generator.

**Comment by Sergio0694** [comment] 2022-07-08 13:29
Yeah this is currently not supported and not planned. The idea is to support this properly with C# 12 via partial properties.

**Closed** 2022-07-08 13:30 UTC
Labels: duplicate :busts_in_silhouette:, mvvm-toolkit :toolbox:
