### ISSUE TITLE
Compilation fails if language version is default

### ISSUE THREAD

**Issue by JkPersson** [CommunityToolkit/dotnet#505] opened 2022-11-17 11:10 UTC
### Describe the bug

I am using Visual Studio 17.5.0 Preview 1.0 with .Net 7 and CommunityToolkit.MVVM 8.1.0-Preview1.
According to the project properties, the compiler defaults to C#11.

When building I get MVVMTK0008 under Analyzers in the Solution Explorer.

Explicitly setting C#11 in the project file fixes the problem.

### Steps to reproduce

```text
Create project and use ObservableProperty -> fail
```

### Expected behavior

Compilation should work with the default setting.

### IDE and version

VS 2022 Preview

### IDE version

 17.5.0 Preview 1.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.1.0-Preview1

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment] 2022-11-17 11:17
What type of project are you using? Since you mentioned that it defaults to C# 11 I assume this is in a .NET 7 project? Can you please also share exactly what errors you're getting when building? Thanks! 🙂

**Comment by JkPersson** [comment] 2022-11-17 11:58
It is a Maui project.

Apart from the MVVMTK0008 i get a lot of "<class> does not contain a definition for <property>"-errors. The latter makes sense since the code generators are not running.

**Comment by Sergio0694** [comment] 2022-11-17 12:06
Do the errors only appear with 8.1? Does it build fine with the MVVM Toolkit 8.0, with everything else remaining the same?

**Comment by JkPersson** [comment] 2022-11-17 13:03
Sorry, I was looking in the wrong part of the tree. I do actually get the error after reupgrading to 8.1.

**Comment by get-flat** [comment] 2022-12-19 20:50
For me, setting LangVersion does not help.

No issues on 8.0. (project MAUI)

After upgrading to 8.1 (and making sure the build is clean -> I had to manually remove bin/ objs/) I'm getting MVVMTK0008.
And also MVVMTK0020 (Invalid use of [ObservableProperty]) although in my repro/test app I do not even use [ObservableProperty].

Is there any other workaround?

**Comment by Sergio0694** [comment] 2022-12-19 20:57
> "And also MVVMTK0020 (Invalid use of [ObservableProperty]) although in my repro/test app I do not even use [ObservableProperty]."

What 😐
Do you have a minimal repro? Is this just in a blank MAUI project? I'm also going to try this.

**Comment by get-flat** [comment] 2022-12-20 09:15
8.1.0-preview2: blank MAUI + test ViewModel
![issue_505](https://user-images.githubusercontent.com/74671895/208626937-458370c7-2b6c-4ede-9541-646670c9297d.png)
```
using CommunityToolkit.Mvvm.ComponentModel;

//#error version

namespace MauiApp3;
public /*partial*/ class MainViewModel : ObservableObject
{
    //[ObservableProperty]
    //int aaa;
}
```
[MauiApp3.zip](https://github.com/CommunityToolkit/dotnet/files/10267010/MauiApp3.zip)

**Comment by Sergio0694** [comment] 2022-12-20 15:49
I'm confused by that screenshot. The error/warning icons on the right (in that orange rectangle) are by design. Those are just icons that VS uses to indicate the level of diagnostics produced by each analyzer. In this case, it's telling you the first two will produce errors, the last 4 will produce warnings. But those icons don't indicate they _are_ emitting diagnostics currently.

**Comment by Sergio0694** [comment] 2022-12-20 15:59
I can't repro with either 8.1.0-preview2 nor 8.1.0-build.1, both work just fine.
I'm on VS 2022 17.4.3, with a blank new MAUI app.
I also tried the attached .zip file, I can build just fine. Closing this as no repro.

> **Note:** if you can only repro this on VS 17.5 Preview and not 17.4, I'd strongly recommend opening an issue for this in the MAUI repo and/or on Roslyn, as it's likely a tooling issue of some sort somewhere else in the stack, not an issue with the MVVM Toolkit per se. Feel free to link this issue there if you do so it's easier for us to follow along. Thank you! 🙂

**Closed by Sergio0694** 2022-12-20 15:59 UTC
Labels: bug :bug:, needs author feedback :memo:, mvvm-toolkit :toolbox:
