### ISSUE TITLE
Duplicating a method with the ICommand attribute breaks source generator

### ISSUE THREAD

**Issue by powerdude** [CommunityToolkit/dotnet#154] opened 2022-03-15 06:20 UTC
Not sure if it's a bigger VS problem or not, but it's a bit disruptive.  Add the following to a view model:

```csharp
[ICommand]
private void DoSomething()
{
}
```

Now, highlight all three lines and press `Ctrl-D` (or copy and paste) at least 3 times.  The ICommandSourceGenerator breaks, the previously generated files disappear and even after adding a unique suffix to each method, it won't create any new files.  The same thing doesn't happen with:

```csharp
[ObservableProperty] int foo;
```

**Comment by Sergio0694** [comment] 2022-03-15 13:04
Hey @powerdude, thank you for reporting this!
I can repro this, the issue is a name collision in the name hints for the generated files. This only happens with the `[ICommand]` generator because it's emitting one file per command, whereas `[ObservableProperty]` combines all generated properties into the same file. I'll make a PR to fix this 🙂

**Comment by Sergio0694** [comment] 2022-03-16 13:09
So, this is also related to https://github.com/dotnet/roslyn/issues/58625, so it needs to be fixed in VS/Roslyn.
That said, I can also add explicit diagnostics for `[ICommand]` though, with a clearer error message.
This might especially help in cases where people try to use `[ICommand]` on multiple overloads of a method.

**Closed** 2022-04-04 18:44 UTC
Labels: bug :bug:, next preview :airplane:, priority 🚩, mvvm-toolkit :toolbox:
