### ISSUE TITLE
[Feature] MVVM Toolkit: allow async reception of messages 

### ISSUE THREAD

**Issue by r2d2rigo** [CommunityToolkit/dotnet#18] opened 2021-01-12 18:21 UTC
## Describe the problem this feature would solve
I have started replacing MvvmLight and Prism with the new MVVM Toolkit and right now I'm loving it. However, I had to use the messaging infrastructure for the first time today and found a small limitation - the default way of processing messages is always run in a synchronous way. I think it would be useful to give the option to process them in an asynchronous way if desired.

## Describe the solution
A very basic implementation would look like this:

    public interface IAsyncRecipient<in TMessage> where TMessage : class
    {
        Task ReceiveAsync(TMessage message);
    }

## Describe alternatives you've considered
Right now I'm manually scheduling a task in `IRecipient.Receive` to process messages that need calling async functions, but feels a bit wrong to do it this way.

## Additional context & Screenshots
None.

**Comment by Sergio0694** [comment] 2021-11-11 11:34
Closing this as by design. Please feel free to comment or open another issue if there's a specific ask 😊

**Closed by Sergio0694** 2021-11-11 11:34 UTC
Labels: by design, feature request :mailbox_with_mail:

**Comment by lennartb-** [comment] 2021-11-15 12:32
We're running into a similar issue, the receiver has an `async Task` method that should be called upon receiving the message. We want to avoid `async void` methods due to [VSTHRD100](https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD100.md). I feel like this is a similar case to https://github.com/CommunityToolkit/WindowsCommunityToolkit/discussions/3961

**Comment by fleed** [comment] 2022-07-09 14:52
Hi @Sergio0694 
I also vote for a "cleaner" implementation using `async Task` rather than `async void`.

**Comment by Sergio0694** [comment] 2022-07-09 15:03
You can already achieve that, see https://github.com/CommunityToolkit/dotnet/issues/332#issuecomment-1172560617 🙂
There just isn't an API to do that as a one-liner.

**Comment by yurislav** [comment] 2023-02-08 13:44
I have created workaround using `CollectionRequestMessage<Task>` to collect tasks from subscribers, so publisher can await asynchronous handlers. Using extensions below, you can have one-liner API for async handlers.

```csharp
using CommunityToolkit.Mvvm.Messaging.Messages;

namespace CommunityToolkit.Mvvm.Messaging;

public class AsyncMessage : CollectionRequestMessage<Task>
{
    readonly CancellationTokenSource? cancellationTokenSource;

    public AsyncMessage()
    {
    }

    public AsyncMessage(CancellationToken cancellationToken)
    {
        this.cancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
    }

    public CancellationToken CancellationToken => cancellationTokenSource?.Token ?? default;
}

public static partial class IMessengerExtensions
{
    public static void Register<TMessage>(this IMessenger messenger, object recipient, Func<object, TMessage, CancellationToken, Task> asyncHandler)
        where TMessage : AsyncMessage
    {
        messenger.Register<TMessage>(recipient, (r, message) =>
        {
            var task = asyncHandler(r, message, message.CancellationToken);
            message.Reply(task);
        });
    }

    public static Task SendAsync<TMessage>(this IMessenger messenger, TMessage message)
        where TMessage : AsyncMessage
    {
        messenger.Send(message);
        return Task.WhenAll(message.Responses);
    }

    public static Task SendAsync<TMessage>(this IMessenger messenger)
        where TMessage : AsyncMessage, new()
        => messenger.SendAsync(new TMessage());
}

```

and usage:

```csharp
async Task MyAsyncHandler(object recipient, AsyncMessage message, CancellationToken cancellationToken)
{
    // ...
}

messenger.Register<AsyncMessage>(this, MyAsyncHandler);
await messenger.SendAsync<AsyncMessage>();
```

**Comment by HakamFostok** [comment] 2023-10-10 18:07
I am shocked how this issue has been closed by suggesting `async void` with very cold blood, as there is nothing wrong with that. and when this comes from Microsoft personnel, it is really unbelievable.
Instead of seeking a real solution for the community's demand, Microsoft, as always, dodges and flees real issues.

**Comment by HakamFostok** [comment] 2023-10-10 18:24
I found [this official suggestion](https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD100.md#event-handlers) is more helpful for the situation.

basically it says call `Task.Run()` from the event handler, not ideal, but of course better than the `async void` suggestion

```
obj.Event += (s, e) => joinableTaskFactory.RunAsync(() => OnEventAsync(s, e));

private async Task OnEventAsync(object sender, EventArgs e)
{
   // async code here.
}
```

**Comment by ClassyCircuit** [comment] 2024-03-01 16:07
@Sergio0694 @r2d2rigo @HakamFostok
> You can already achieve that, see [#332 (comment)](https://github.com/CommunityToolkit/dotnet/issues/332#issuecomment-1172560617) 🙂 There just isn't an API to do that as a one-liner.

I have built upon @yurislav code and implemented necessary extension methods to make this as close as possible to a one-liner:

```.cs
    public static partial class IMessengerExtensions
    {
        public static void Register<TMessage>(this IMessenger messenger, IAsyncRecipient<TMessage> recipient)
            where TMessage : AsyncMessage
        {
            messenger.Register<TMessage>(recipient, (r, message) =>
            {
                if (r is IAsyncRecipient<TMessage> asyncRecipient)
                {
                    var task = asyncRecipient.ReceiveAsync(message, message.CancellationToken);
                    message.Reply(task);
                }
            });
        }

        public static Task SendAsync<TMessage>(this IMessenger messenger, TMessage message)
            where TMessage : AsyncMessage
        {
            messenger.Send(message);
            return Task.WhenAll(message.Responses);
        }

        public static Task SendAsync<TMessage>(this IMessenger messenger)
            where TMessage : AsyncMessage, new()
        {
            return messenger.SendAsync(new TMessage());
        }
    }

    public class AsyncMessage : CollectionRequestMessage<Task>
    {
        private readonly CancellationTokenSource? _cancellationTokenSource;

        protected AsyncMessage(CancellationToken cancellationToken = default)
        {
            _cancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
        }

        public CancellationToken CancellationToken => _cancellationTokenSource?.Token ?? default;
    }

    public class AsyncMessage<T> : AsyncMessage
    {
        public T Value { get; }

        public AsyncMessage(T value, CancellationToken cancellationToken = default) : base(cancellationToken)
        {
            Value = value;
        }
    }

    public interface IAsyncRecipient<TMessage>
        where TMessage : AsyncMessage
    {
        Task ReceiveAsync(TMessage message, CancellationToken cancellationToken);
    }

```

This is how you use it:

```.cs

public class TestRecipient : EnhancedObservableRecipient, IAsyncRecipient<TestMessage>
{
    public bool MessageReceived { get; set; } = false;

    public async Task ReceiveAsync(TestMessage message, CancellationToken cancellationToken)
    {
        MessageReceived = true;
        await Task.CompletedTask;
    }
}

public class TestMessage : AsyncMessage<TestPayload>
{
    public TestMessage(TestPayload value) : base(value) { }
}

public class TestPayload
{
    public string SomeValue { get; set; }

    public TestPayload(string someValue)
    {
        SomeValue = someValue;
    }
}

public class TestSender : ObservableObject
{
    public async Task SendTestMessageAsync()
    {
        await WeakReferenceMessenger.Default.SendAsync(new TestMessage(new TestPayload("Test")));
    }
}
```

And the best part is registration is handled automatically by an extension to ObservableRecipient class:

```.cs

public abstract class EnhancedObservableRecipient : ObservableRecipient
{
    // Cache reflection results.
    private static readonly MethodInfo RegisterMethodInfo = typeof(IMessengerExtensions)
        .GetMethod(nameof(IMessengerExtensions.Register), BindingFlags.Public | BindingFlags.Static);
    private static readonly MethodInfo UnregisterMethodInfo = typeof(IMessenger)
        .GetMethod("Unregister", new[] { typeof(object) });


    protected override void OnActivated()
    {
        base.OnActivated();
        RegisterAsyncHandlers();
    }

    protected override void OnDeactivated()
    {
        UnregisterAsyncHandlers();
        base.OnDeactivated();
    }

    private void RegisterAsyncHandlers()
    {
        var asyncRecipientInterfaces = this.GetType().GetInterfaces()
            .Where(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IAsyncRecipient<>));

        foreach (var iface in asyncRecipientInterfaces)
        {
            var messageType = iface.GetGenericArguments()[0];
            if (RegisterMethodInfo != null)
            {
                var registerMethod = RegisterMethodInfo.MakeGenericMethod(messageType);
                registerMethod.Invoke(null, new object[] { Messenger, this });
            }
        }
    }

    private void UnregisterAsyncHandlers()
    {
        var interfaces = GetType().GetInterfaces()
            .Where(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IAsyncRecipient<>));

        foreach (var iface in interfaces)
        {
            var messageType = iface.GetGenericArguments().First();
            if (UnregisterMethodInfo != null)
            {
                var genericMethod = UnregisterMethodInfo.MakeGenericMethod(messageType);
                genericMethod.Invoke(Messenger, new object[] { this });
            }
        }
    }
}
```

So as you can see this comes as close as possible to the regular way of sending messages.

For those who don't want to use `EnhancedObservableRecipient`, you can just register your classes manually in recipient constructor like this: `Messenger.Register<TestMessage(this);`

It would be nice if this was added to the library, but I don't know all your codebase and your guidelines, so I haven't opened a PR, but I imagine it would be easy for some regular contributor to add this. Adding this would also increase performance by using Roslyn source code generators instead of using reflection for activation and deactivation phases in EnhancedObservableRecipient.

**Comment by flier268** [comment] 2024-09-22 02:50
This is a easy way to request an async response

```C#
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
        // reply a Task immediately
        WeakReferenceMessenger.Default.Register<FileDialogRequestMessage>(this, ((recipient, message) => message.Reply(HandleFileDialogRequest(recipient, message))));
    }

    private async Task<string?> HandleFileDialogRequest(object recipient, FileDialogRequestMessage message)
    {
        var window = (MainWindow)recipient;
        var filePickerOptions = new FilePickerOpenOptions
        {
            Title = message.Title,
            FileTypeFilter = new[]
            {
                new FilePickerFileType("Allowed Files") { Patterns = message.FileTypes }
            },
            AllowMultiple = false
        };
        var result = await window.StorageProvider.OpenFilePickerAsync(filePickerOptions);

        string? response = result.Count > 0 ? result[0].Path.LocalPath : null;
        return response;
    }
}
```
```C#
[RelayCommand]
    private async Task BrowseExecutableAsync()
    {
        var message = new FileDialogRequestMessage("Select Executable", new[] { "*.exe" });
        // double await
        var response =await await WeakReferenceMessenger.Default.Send(message);

        if (!string.IsNullOrEmpty(response))
        {
            SelectedProject.ExecutablePath = response;
        }
    }
```
```C#
// message response a Task
public class FileDialogRequestMessage(string title, string[] fileTypes) : AsyncRequestMessage<Task<string?>>
{
    public string Title { get; } = title;
    public string[] FileTypes { get; } = fileTypes;
}
```

**Comment by CodingOctocat** [comment] 2025-04-06 01:31
If you need a simple implementation of:

```cs
public class AsyncActionRequestMessage<TTag, TResponse> : AsyncRequestMessage<TResponse>
{
    public TTag? Tag { get; set; }

    public AsyncActionRequestMessage(TTag? tag)
    {
        Tag = tag;
    }
}

Messenger.Register<AsyncActionRequestMessage<string, bool>, string>(this, "SaveAsync",
    (r, m) => m.Reply(SaveAsync(m.Tag)));

await Messenger.Send(new AsyncActionRequestMessage<string, bool>(result.FilePath), "SaveAsync").Response;
```

**Comment by lloydjatkinson** [comment] 2026-01-08 17:49
@lennartb- I think I understand, but my problems with this are: 1) I'm using `ValueChangedMessage` 2) I don't think any of my usages so far need a response and for some reason the there is no `AsyncValueChanged` or `AsyncMessage` only `AsyncRequestMessage`, 3) Even when using an async request message, `IRecipient` implementation still has to be `void` or `async` void.

```cs
    public class DirectorySelectedMessage : AsyncRequestMessage<Task>
    {
        public string DirectoryPath { get; }

        public DirectorySelectedMessage(string directoryPath)
        {
            this.DirectoryPath = directoryPath;
        }
    }

    // First view model:
    //this.messenger.Send(new DirectorySelectedMessage(result.LocalPath));
    await this.messenger.Send(new DirectorySelectedMessage(result.LocalPath));


    // Second view model:
    public partial class SecondViewModel :
        ObservableRecipient,
        IRecipient<DirectorySelectedMessage>
    {
        public void Receive(DirectorySelectedMessage message)
        {
            throw new NotImplementedException();
        }
    }
```
