### ISSUE TITLE
Allow `ObservableObject` to implement interface that derives from `INotifyPropertyChanged`

### ISSUE THREAD

**Issue by karmeye** [CommunityToolkit/dotnet#990] opened 2024-11-15 05:21 UTC
### Overview

Example

```csharp

interface MyInterface : INotifyPropertyChanged
{
    bool MyBool { get; }
}

[ObservableObject]
public partial class MyViewModel: ViewModel, IMyInterface
{

    [ObservableProperty]
    public partial bool MyBool { get; set; } = true;
} 
```

This results in build error:

> MVVMTK0002: Cannot apply [ObservableObject] to type MyViewModel, as it already declares the INotifyPropertyChanged interface (https://aka.ms/mvvmtoolkit/errors/mvvmtk0002)

What does it matter if it declares it? It hasn't implemented it. The implementation would be done by the source generator. Or is there some technical reason this isn't allowed?

Thx

### API breakdown

```csharp

interface MyInterface : INotifyPropertyChanged
{
    bool MyBool { get; }
}

[ObservableObject]
public partial class MyViewModel: ViewModel, IMyInterface
{

    [ObservableProperty]
    public partial bool MyBool { get; set; } = true;
} 
```

### Usage example

```csharp

interface MyInterface : INotifyPropertyChanged
{
    bool MyBool { get; }
}

[ObservableObject]
public partial class MyViewModel: ViewModel, IMyInterface
{

    [ObservableProperty]
    public partial bool MyBool { get; set; } = true;
} 
```

### Breaking change?

No

### Alternatives

.

### Help us help you

No, just wanted to propose this

**Comment by hawkerm** [comment] 2024-11-23 09:05
Duplicate of #620

**Closed** 2024-11-23 20:27 UTC
Labels: feature request :mailbox_with_mail:
