### ISSUE TITLE
Add attribute to declare `[ObservableProperty]` dependencies on dependent property

### ISSUE THREAD

**Issue by kaivol** [CommunityToolkit/dotnet#377] opened 2022-08-11 10:49 UTC
### Overview

Declaring all dependent properties on the `[ObservableProperty]` can quickly become confusing. 
I think it would be easier/clearer if the dependencies could be declared using an attribute directly on the dependent property.

### API breakdown

Possible attribute name: `[DependsOn(...)]`

```csharp
[AttributeUsage(AttributeTargets.Property, AllowMultiple = true)]
public sealed class DependsOnAttribute : Attribute
{ 
    public DependsOnAttribute(string propertyName)
    {
        PropertyNames = new[] { propertyName };
    }

    public DependsOnAttribute(string propertyName, params string[] otherPropertyNames)
    {
        PropertyNames = new[] { propertyName }.Concat(otherPropertyNames).ToArray();
    }

    public string[] PropertyNames { get; }
 }
```

### Usage example

```csharp
public sealed partial class PersonViewModel : ObservableObject
{
    [ObservableProperty]
    private string name;

    [ObservableProperty]
    private string surname;

    [DependsOn(nameof(Name), nameof(Surname))]
    public string FullName => $"{Name} {Surname}";
}
```

<details>
  <summary>Generated code</summary>

  ```csharp
  public sealed partial class PersonViewModel
  {
      public string Name
      {
          get => name;
          set
          {
              if (!global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(name, value))
              {
                  OnPropertyChanging();
                  name = value;
                  OnPropertyChanged();
                  OnPropertyChanged("FullName");
              }
          }
      }

      public string Surname
      {
          get => surname;
          set
          {
              if (!global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(surname, value))
              {
                  OnPropertyChanging();
                  surname = value;
                  OnPropertyChanged();
                  OnPropertyChanged("FullName");
              }
          }
      }
  }
  ```
</details>

### Breaking change?

No

### Alternatives

Keep using `[NotifyPropertyChangedFor] `

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by kaivol** [comment] 2022-09-08 15:47
So I just went ahead and implemented this feature [here](https://github.com/CommunityToolkit/dotnet/compare/main...kaivol:DotnetCommunityToolkit:dependson), in case anyone wants to try it out

**Comment by Sergio0694** [comment] 2022-09-08 16:56
Duplicate of #https://github.com/CommunityToolkit/dotnet/issues/367.

**Closed by Sergio0694** 2022-09-08 16:56 UTC
Labels: feature request :mailbox_with_mail:

**Comment by MisinformedDNA** [comment] 2022-09-20 17:49
@kaivol Would you be interested in creating a separate NuGet package for this?
