### ISSUE TITLE
Mvvm toolkit - Source generator: [ICommand] attribute fails to generate codes in .NET MAUI

### ISSUE THREAD

**Issue by azthrun** [CommunityToolkit/dotnet#186] opened 2022-03-30 04:30 UTC
### Describe the bug

In a .NET MAUI project, [ICommand] source generator sometimes fails to generator codes for the assign method(s), or it only generates for some of the platforms.

### Steps to reproduce

```text
1. Create a .NET MAUI (preview) project.
2. Install the CommunityToolkit.Mvvm package, version 8.0.0-preview1 or preview2.
3. Create a class that extends ObservableObject.
4. Create a method and add the [ICommand] attribute to the method. (Source generator does generate codes at this step)
5. Continue adding more codes such as new View/ViewModel. Can't say for sure when it will start to fail. I usually start noticing the auto-generate codes disappear after adding one or two more view models classes (each with only one observable property and one method that uses [ICommand] attribute.
```

### Expected behavior

All view models using [ICommand] attribute should have a partial class generated in each platform that the .NET Maui project targets.

### Screenshots

![image](https://user-images.githubusercontent.com/26609376/160750438-74360105-d70e-4f61-9426-ea3effc32276.png)

### IDE and version

VS 2022 Preview

### IDE version

Version 17.2.0 Preview 2.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0-preview1 & preview2

### Help us help you

No, just wanted to report this

**Comment by pictos** [comment] 2022-04-15 23:20
@azthrun 
Could you attach a small repro? I tried on my end and I can't reproduce the issue.
[Repro.zip](https://github.com/CommunityToolkit/dotnet/files/8498875/Repro.zip)

**Comment by azthrun** [comment] 2022-04-16 16:18
Hello @pictos 
I tried but was not able to reproduce it on my side neither.
Need to mention that my VS22 was updated to preview 3.0. Not sure if any changes from the update made a difference.

**Comment by pictos** [comment] 2022-04-16 16:19
Could be. @michael-hawker I think that we can close this issue

**Closed** 2022-04-18 17:05 UTC
Labels: bug :bug:, unable to reproduce :heavy_multiplication_x:, mvvm-toolkit :toolbox:
