### ISSUE TITLE
Version 8.3.0 crash on windows .net maui app

### ISSUE THREAD

**Issue by Mbprogramming** [CommunityToolkit/dotnet#936] opened 2024-09-03 11:06 UTC
### Describe the bug

Using Version 8.3.0 on windows .net maui app crashs on using the first toolkit derived class

![image](https://github.com/user-attachments/assets/07f1e417-46b2-4272-a406-a7516dd7871f)

### Regression

8.2.2

### Steps to reproduce

```text
create .net maui app in VS
create a class Test, derive from ObservableObject with one ObservableProperty

public partial class Test: ObservableObject
    {
        [ObservableProperty]
        private string _willi = "";
    }

instantiate the class

var test = new Test();
test.Willi = "Hallo Willi";

Crash!
```

### Expected behavior

no crash

### Screenshots

![image](https://github.com/user-attachments/assets/07f1e417-46b2-4272-a406-a7516dd7871f)

### IDE and version

VS 2022, VS 2022 Preview

### IDE version

Version 17.12.0 Preview 1.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.3.0

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment] 2024-09-03 16:14
Duplicate of #923, the workaround is in https://github.com/CommunityToolkit/dotnet/issues/923#issuecomment-2314444048 🙂

**Closed by Sergio0694** 2024-09-03 16:14 UTC
Labels: bug :bug:
