### ISSUE TITLE
Observable Property Generator Errors

### ISSUE THREAD

**Issue by QJS-RH** [CommunityToolkit/dotnet#410] opened 2022-08-29 23:41 UTC
NEW WPF Application.
Add Community.Toolkit.Mvvm V8.0.0
Add MainWindowVM class as

`public partial class MainWindowVM : ObservableObject
    {
        public MainWindowVM()
        {
            ApplicationName = "RHOKS Automation";
        }

        private string? m_ApplicationName;
        public string? ApplicationName
        {
            get => m_ApplicationName;
            set => SetProperty(ref m_ApplicationName, value);
        }

        //[ObservableProperty]
        //private string? m_ApplicationName;

    }`

Build works OK.

Change Class to 

`public partial class MainWindowVM : ObservableObject
        {
            public MainWindowVM()
            {
                ApplicationName = "RHOKS Automation";
            }

            [ObservableProperty]
            private string? m_ApplicationName;

        }`
<img width="1195" alt="17Errors" src="https://user-images.githubusercontent.com/10412049/187317378-eeceea9c-f33d-4614-8540-238bee332d85.PNG">

17 Errors Appear

Just upgraded to VS 17.3.2
VS Pro 2022 64-bit

**Comment by FormatException** [comment] 2022-08-31 21:48
I haven't updated yet (VS 17.3.0) and I have the exact same issue with the simplest of projects.  My project is .net 6.

`
public partial class MainWindowViewModel : ObservableObject
    {
        [ObservableProperty]
        [NotifyPropertyChangedFor(nameof(ExpandedWidth))]
        private bool isExpanded;

        public GridLength ExpandedWidth
        {
            get
            {
                if (IsExpanded)
                    return new GridLength(1, GridUnitType.Star);
                return new GridLength(0);
            }
        }
    }
`

![image](https://user-images.githubusercontent.com/5240258/187790789-852970b4-e010-45e6-ba2a-0e15f52a89e7.png)

**Comment by FormatException** [comment] 2022-08-31 21:55
This is all likely a dupe of #343

**Comment by saintdianabless** [comment] 2022-09-01 16:37
which .net version is working for this lib?
i create a viewmodel and mark a method with [RelayCommand]
* when i use .net 6(lastest vs2022 preview), it says that there is "CS0102: xxxxx already contains a definition xxxxx"
* when i switch to .net framework 4.7.2, it seems that there is nothing generated.

**Comment by FormatException** [comment] 2022-09-01 17:27
> which .net version is working for those Attributes used as generator? i create a viewmodel and mark a method with [RelayCommand]
> 
> * when i use .net 6(lastest vs2022 preview), it says that there is "CS0102: xxxxx already contains a definition xxxxx"
> * when i switch to .net framework 4.7.2, it seems that there is nothing generated.

I never could get it to generate right with .net framework.  I was trying with .net framework 4.8.  I switched to .net 6 and only then would it generate.

**Comment by saintdianabless** [comment] 2022-09-01 17:40
> 
![图片](https://user-images.githubusercontent.com/93075932/187977124-d8fe93ca-034b-4b1b-b652-01af80167dd9.png)

Yes, switched to .net 6, it works, and.......works again. But I didn't find where the other definition is.

**Comment by MisinformedDNA** [comment] 2022-09-02 16:36
If this is in a WPF app, you can try moving the view model to a separate class project or follow [this workaround](https://github.com/dotnet/wpf/issues/6792#issuecomment-1183633402).

**Comment by Sergio0694** [comment] 2022-09-13 17:15
I think the official fix isn't out just yet.
@jkrusso have you tried this one? It _should_ fix it: https://github.com/dotnet/wpf/issues/6792#issuecomment-1183633402.

**Comment by jkrusso** [comment] 2022-09-13 20:31
@Sergio0694  Yes, that workaround seems to work. Thanks

**Closed** 2022-12-18 02:53 UTC
