### ISSUE TITLE
[Feature] Add ability to specify the access modifier of the property getter and setter.

### ISSUE THREAD

**Issue by Kiryuumaru** [CommunityToolkit/dotnet#416] opened 2022-09-03 06:47 UTC
### Overview

I cannot use the source code generator to generate the property getter or setter access modifier. I have to do it by implementing the property manually and calling the generated SetProperty.

### API breakdown

An additional parameter for the ObservablePropertyAttribute to specify the access modifier of the property getter and setter.

### Usage example

```CSharp
[ObservableObject]
public partial class Person
{
    [ObservableProperty(Setter = AccessModifier.Private)]
    string? phoneNumber;

    public void UpdatePhoneNumber(string phoneNumber)
    {
        if (SomeUtil.CheckPhoneNumberIsValid(phoneNumber))
        {
            PhoneNumber = phoneNumber;
        }
    }
}
```
Will generate
```CSharp
public partial class Person
{
    public string? PhoneNumber
    {
        get => phoneNumber;
        private set => SetProperty(ref phoneNumber, value);
    }

    public void UpdatePhoneNumber(string? phoneNumber)
    {
        if (SomeUtil.CheckPhoneNumberIsValid(phoneNumber))
        {
            PhoneNumber = phoneNumber;
        }
    }
}
```

### Breaking change?

No

### Alternatives

I manually implement the property
```CSharp
[ObservableObject]
public partial class Person
{
    string? phoneNumber;
    public string? PhoneNumber
    {
        get => phoneNumber;
        private set => SetProperty(ref phoneNumber, value);
    }

    public void UpdatePhoneNumber(string? phoneNumber)
    {
        if (SomeUtil.CheckPhoneNumberIsValid(phoneNumber))
        {
            PhoneNumber = phoneNumber;
        }
    }
}
```

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment] 2022-09-03 12:02
Duplicate of #291.

**Closed by Sergio0694** 2022-09-03 12:02 UTC
Labels: feature request :mailbox_with_mail:
