### ISSUE TITLE
SourceGenerator shows CS8785 warning (MissingMethodException) in the error list

### ISSUE THREAD

**Issue by laolarou726** [CommunityToolkit/dotnet#546] opened 2022-12-27 20:35 UTC
### Describe the bug

SourceGenerator shows CS8785 warning in the error list:

“ObservablePropertyGenerator”
“ObservableObjectGenerator”
“INotifyPropertyChangedGenerator”

WARN	CS8785	Generator “RelayCommandGenerator” Failed to generate source. "Could not find method: “System.ReadOnlySpan`1<!0> System.Collections.Immutable.ImmutableArray`1.AsSpan()”。”	LauncherX.Avalonia	C:\Users\luoli\Documents\GitHub\LauncherX.Avalonia\LauncherX.Avalonia\CSC	1

### Steps to reproduce

```text
I don't have reproduction at this time.
```

### Expected behavior

There should be no warnings in the error list.

### IDE and version

VS 2022

### IDE version

17.4.3

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment] 2022-12-27 20:43
Possibly a duplicate of #493? Are you using CsWin32 by any chance?

**Comment by laolarou726** [comment] 2022-12-27 20:49
> Possibly a duplicate of #493? Are you using CsWin32 by any chance?

Yes. I just started using CSWin32. Then the warning shows.

**Comment by Sergio0694** [comment] 2022-12-27 20:50
Closing this as duplicate then, as it's the same issue 🙂

**Closed by Sergio0694** 2022-12-27 20:50 UTC
Labels: bug :bug:, needs author feedback :memo:, mvvm-toolkit :toolbox:
