### ISSUE TITLE
Add support for "required" and "virtual" keywords to property generator

### ISSUE THREAD

**Issue by michael-tlsoftware** [CommunityToolkit/dotnet#679] opened 2023-05-01 21:49 UTC
### Overview

When working with nullable libraries, being able to add the required keyword to properties is helpful. I have reviewed the source generator and dont believe this is currently supported when using ObservablePropertyAttribute . I propose adding properties to the this class to signal to the generator to add this modifier where required. This would default to false to not impact existing usage.

As the code would be similar, I propose to add the virtual modifier at the same time for completeness.

### API breakdown

```csharp
[AttributeUsage(AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
public sealed class ObservablePropertyAttribute : Attribute
{
    public bool Virtual { get; set; } = false;
    public bool Required { get; set; } = false;
}
```
### Usage example

```csharp
[ObservableProperty(Required = true, Virtual = true)]
bool _myProperty;
```
### Breaking change?

No

### Alternatives

Current alternative is to selectively use source generator, and use the underlying methods when creating properties by hand.

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by Sergio0694** [comment] 2023-05-01 21:51
Duplicate of #291.
Superseded by #555.

**Closed by Sergio0694** 2023-05-01 21:51 UTC
Labels: feature request :mailbox_with_mail:, mvvm-toolkit :toolbox:
