### ISSUE TITLE
MAUI app can't start with MVVM toolkit v8.3.0 (WinRT not found)

### ISSUE THREAD

**Issue by Dokug** [CommunityToolkit/dotnet#924] opened 2024-08-28 09:15 UTC
### Describe the bug

When updating the `CommunityToolkit.Mvvm` package from 8.2.2 to 8.3.0, my .net MAUI app fails to launch with the following information in the Windows platform-specific `App.xaml.cs` file:

![image](https://github.com/user-attachments/assets/6d551d6f-28d3-444f-be6b-b13e322eda48)

It seems to have something to do with different versions of WinRT that are called for some reason.

### Regression

8.2.2

### Steps to reproduce

1. Create a .net MAUI project
2. Add the dependency:
```
<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.0" />
```
3. Add the following class:
```
using CommunityToolkit.Mvvm.ComponentModel;

namespace MauiTest;

internal partial class ViewModel : ObservableObject
{
    [ObservableProperty]
    private int _number = 0;
}

```
4. Change the `MainPage.xaml` to the following:
```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MauiTest"
             x:Class="MauiTest.MainPage"
             x:DataType="local:ViewModel">
    <ContentPage.BindingContext>
        <local:ViewModel />
    </ContentPage.BindingContext>

            <Button
                x:Name="CounterBtn"
                Text="{Binding Number}" 
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Fill" />

</ContentPage>
```

5. Add the demo view model to the depency injection in `MauiProgram.cs`:
```
builder.Services.AddSingleton<ViewModel>();
```

6. Build the project on Windows and observe the error

### Expected behavior

The app should build and run

### Screenshots

![image](https://github.com/user-attachments/assets/6d551d6f-28d3-444f-be6b-b13e322eda48)

### IDE and version

VS 2022, VS 2022 Preview

### IDE version

Version 17.12.0 Preview 1.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.3.0

### Help us help you

No, just wanted to report this

**Comment by kebox7** [comment] 2024-08-28 09:38
@Dokug, possible solution: #923

**Comment by LeDahu22** [comment] 2024-08-28 12:19
> @Dokug, possible solution: [#923 (comment)](https://github.com/CommunityToolkit/dotnet/issues/923#issuecomment-2314444048)

Exact same problem indeed !

**Comment by hwsmo** [comment] 2024-08-28 12:21
Same here. A show stopper.

**Comment by Sergio0694** [comment] 2024-08-28 16:01
Duplicate of #923, the fix is mentioned in https://github.com/CommunityToolkit/dotnet/issues/923#issuecomment-2314444048.

**Closed by Sergio0694** 2024-08-28 16:01 UTC
Labels: duplicate :busts_in_silhouette:
