### ISSUE TITLE
[Feature] Specify the generated ObservableProperty name

### ISSUE THREAD

**Issue by blueshift777** [CommunityToolkit/dotnet#795] opened 2023-11-14 00:25 UTC
I would like to contribute an update to the ObservableProperty attribute that would allow the user to specify the resulting property name.  This would involve adding a string property, SpecifiedPropertyName, to the ObservableProperty attribute class in addition to a new, overloaded constructor that accepts the specified property name as a parameter.  If the SpecifiedPropertyName is not null or whitespace, the property with the specified name is generated.  Otherwise, the current method for generating the property name will be used.  For example, 

```
[ObservableProperty("SpecialValue")]
private double value;
```

will generate the observable property,

```
public double SpecialValue
{
    get => value;
    set
    {
        if (!global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(this.value, value))
        {
            OnSpecialValueChanging(value);
            OnSpecialValueChanging(default, value);
            OnPropertyChanging(global::CommunityToolkit.Mvvm.ComponentModel.__Internals.__KnownINotifyPropertyChangingArgs.SpecialValue);
            this.value = value;
            OnSpecialValueChanged(value);
            OnSpecialValueChanged(default, value);
            OnPropertyChanged(global::CommunityToolkit.Mvvm.ComponentModel.__Internals.__KnownINotifyPropertyChangedArgs.SpecialValue);
        }
    }
}
```

The purpose of this feature is to allow users to specify the property name when the private member variable does not follow common naming conventions.

**Comment by Sergio0694** [comment] 2024-08-21 20:25
Duplicate of #706.
Superseded by #555.

This is also a duplicate of #835, please avoid opening the same proposal multiple times 🙂

**Closed by Sergio0694** 2024-08-21 20:25 UTC
Labels: needs triage :mag:
