### ISSUE TITLE
Exception raised in an async command handler method disables the command though the exception is handled

### ISSUE THREAD

**Issue by egvijayanand** [CommunityToolkit/dotnet#164] opened 2022-03-17 15:15 UTC
### Describe the bug

Using v8.0.0-preview2 MVVM Toolkit NuGet package.

Exception raised in an async command handler method disables the command though the exception is handled.

Have a look at the below code snippet:

The developer is certain about the possibility of an exception, so a try ... catch block is introduced to handle the exception. In this case, the exception is handled, the command should not move into the disabled state and should continue to work as before.

```cs
private async Task DoSomething()
{
    try
    {
        // Execute the logic and it raises an exception
    }
    catch (Exception ex)
    {
        // Handle the exception
    }
}
```

### Regression

NA

### Steps to reproduce

```text
1. Add the v8.0.0-preview2 version of the MVVM Toolkit NuGet package
2. Add a new class and inherit from ObservableObject
3. Add an async method with a try ... catch construct to handle errors
4. Decorate the method with [ICommand] attribute
5. Verify the Command's CanExecute() method's output before- and after- the exception is raised and handled
```

### Expected behavior

Since the exception is handled by the developer code, the command should not move into the disabled state and continue to work as before.

### Screenshots

NA

### IDE and version

VS 2022 Preview

### IDE version

17.2.0 Preview 2.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Additional context

NA

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment] 2022-03-18 11:30
Pretty sure this is actually unrelated from the exception, and just caused by the bug in Preview2 that caused async commands with no concurrent execution (which is now the default setting) not to be enabled again after the first execution. This is essentially a duplicate of #149, and was fixed in #139. Could you try with the latest package from our daily feed (`https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json`) to verify that this works? Thanks! 🙂

**Comment by egvijayanand** [comment] 2022-03-25 04:44
As communicated, validated it with nightly build `8.0.0-build.94` from the internal CI feed and found it to be working as expected.

Kindly include the fix in the next preview release if it meets other criteria.

**Comment by Sergio0694** [comment] 2022-03-25 22:24
Yup, everything that's on main will go into the next preview release 😄
Closing this as it's resolved then, thank you!

**Closed by Sergio0694** 2022-03-25 22:24 UTC
Labels: bug :bug:, needs author feedback :memo:, mvvm-toolkit :toolbox:
