### ISSUE TITLE
Add an option to [ObservableProperty]  - generate a private setter

### ISSUE THREAD

**Issue by stepagrus** [CommunityToolkit/dotnet#840] opened 2024-02-20 13:43 UTC
### Overview

Hello! 

I need a private setter when generating an observable property.

For example:
```
  [ObservableProperty(privateSetter: true)]
  private bool _isValid;
```

Will generate the following code (code simplified to make it easier to read):

```
public bool IsValid
{
    get => _isValid;
    private set
    {
        if (EqualityComparer<bool>.Default.Equals(_isValid, value))
        {
            _isValid = value;
            OnPropertyChanged();
        }
    }
}
```

### API breakdown

no breakdowns

### Usage example

```
  [ObservableProperty(privateSetter: true)]
  private bool _isValid;
```

### Breaking change?

No

### Alternatives

-

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment] 2024-02-20 17:27
Duplicate of #291.
Superseded by #555.

**Closed by Sergio0694** 2024-02-20 17:27 UTC
Labels: feature request :mailbox_with_mail:

**Comment by stepagrus** [comment] 2024-02-21 04:37
Thank you. We will wait for partial properties to be delivered
