### ISSUE TITLE
Build fails when using WeakReferenceMessenger in .NET 5 project

### ISSUE THREAD

**Issue by alexdefine** [CommunityToolkit/dotnet#455] opened 2022-09-27 12:16 UTC
### Describe the bug

Project doesn't build whenever there is a **WeakReferenceMessenger** usage (Register, Send).
Problem is that there is an auto-generated code that uses **DynamicallyAccessedMembersAttribute** on a some class.
In .NET 5 this attribute is not allowed on classes [docs.](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.dynamicallyaccessedmembersattribute?view=net-5.0), that possibility was added in .NET 6 [docs](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.dynamicallyaccessedmembersattribute?view=net-6.0)

### Regression

First time trying CommunityToolkit.Mvvm. Love it btw!

### Steps to reproduce

```text
1. Create any .net 5 project (console app is used for this instance)
2. Create class, inherit ValueChangedMessage
3. Create class, inherit IRecipient<>
5. In Main Register recipient and call Send
```

### Expected behavior

No errors during build

### Screenshots

![image](https://user-images.githubusercontent.com/14275613/192523526-0a7636f4-82e8-46ad-9273-444a626b4ac6.png)

### IDE and version

VS 2022

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment] 2022-09-27 12:18
Closing as by design, [.NET 5 is EOL](https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/) and not supported.

**Closed by Sergio0694** 2022-09-27 12:18 UTC
Labels: bug :bug:

**Comment by alexdefine** [comment] 2022-09-27 12:23
![image](https://user-images.githubusercontent.com/14275613/192525103-6b7685cd-437b-43e2-b3be-6fa568425c18.png)

@Sergio0694, this is not entirely true, in that case. It **partially** works in .NET 5.

or am I missing something.

**Comment by Sergio0694** [comment] 2022-09-27 12:38
Those are the wrong docs, the new ones are at https://aka.ms/mvvmtoolkit/docs. We'll eventually remove the old ones 🙂

> "It partially works in .NET 5."

That is correct, but it's not supported. Meaning it may or may not work, and we won't provide support when it doesn't.

**Comment by alexdefine** [comment] 2022-09-27 14:32
> 

got it, thanks for the link!
