### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by xwang-888** [CommunityToolkit/dotnet#381] opened 2022-08-15 09:35 UTC
### Describe the bug

After I add fields, repeated error prompts always appear.

### Steps to reproduce

```text
Create a project, add community toolkit.mvvm,
```

### Expected behavior

What is the cause

### Screenshots

![image](https://user-images.githubusercontent.com/56998197/184611805-c773c762-0e97-4bb0-990e-d3918e6b96ea.png)
![image](https://user-images.githubusercontent.com/56998197/184612423-7ebc4a0b-a629-488b-a785-9d2ba3ff5a33.png)

### IDE and version

VS 2022

### IDE version

17.3.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by Firito** [comment] 2022-08-15 09:42
I have the same problem, The condition of the problem is added ”xmlns:xxx="clr-namespace:namespace.xxx“ in the xaml

**Comment by Firito** [comment] 2022-08-15 10:40
# Min Steps to reproduce

## Steps
1. create net6.0 wpf app
2. use CommunityToolkit.Mvvm nuget packages
3. Create a ViewModel, and create a property via ObservablePropertyAttribute, like:
![image](https://user-images.githubusercontent.com/23100870/184619704-396c75c9-4992-4f8e-9b76-5306b29526ff.png)
4. add xmlns:local="clr-namespace:Demo" in MianWidow
![image](https://user-images.githubusercontent.com/23100870/184620798-1f803332-b0b7-4880-a562-3e937027e5d3.png)
5.build the project （error!!!）

## IDE and version
VS 2022

## IDE version
17.3.0

## Nuget packages
 CommunityToolkit.Mvvm

##Nuget package version(s)
8.0.0

**Comment by LiuFu2014** [comment] 2022-08-17 05:48
+1

**Comment by sdhongjun** [comment] 2022-08-28 06:58
If you remove `xmlns:local="clr-namespace:Demo"` declare from xaml file the errors was gone, but we must use it. What cause this issue?

**Comment by Sergio0694** [comment] 2022-12-18 02:57
Likely a duplicate of #https://github.com/CommunityToolkit/dotnet/issues/343, should be fixed now with the latest SDK 🙂

**Closed by Sergio0694** 2022-12-18 02:57 UTC
Labels: bug :bug:
