### ISSUE TITLE
[Feature] Use CallerArgumentExpression in Guard

### ISSUE THREAD

**Issue by RedX2501** [CommunityToolkit/dotnet#351] opened 2022-07-20 14:30 UTC
### Describe the problem

The nuget for Microsoft.Toolkit.Diagnostics repostiory link to this repo. Not sure whether this is the correct place for this feature request as I can't find any code implementing Guard here.

Since I can't find the code I can't see if this has been implemented yet.

Searching the code and issues for `CallerArgumentExpression` has returned no results.

Currently it is necessary to pass the argument name as an extra parameter in various Guard calls.

### Describe the solution

With [CallerArgumentExpression](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#callerargumentexpression-attribute-diagnostics) introduced in C# 10 this would no longer be necessary.

**Comment by Sergio0694** [comment] 2022-07-21 20:32
Duplicate of #3, already fixed by #29 and available in the preview releases 🙂

**Closed by Sergio0694** 2022-07-21 20:32 UTC
Labels: feature request :mailbox_with_mail:, diagnostics 🔬, fixed in main :racing_car:
