### ISSUE TITLE
WPF XAML designer doesn't show ObservableProperty

### ISSUE THREAD

**Issue by AignerGames** [CommunityToolkit/dotnet#341] opened 2022-07-09 06:46 UTC
### Describe the bug

VisualStudio 2022 Version 17.2.4
Toolkit.Mvvm 7.1.2

I set d:DataContext="{d:DesignInstance Type=local:ViewModel}" in the WPF XAML designer to get code completion hints, which works fine for my public properties.

But when I use the [ObservableProperty] attribute on fields to auto generate the property, the XAML designer will not detect / show the generated properties (but it will show the public properties which I added "by hand" so it uses the correct design instance type)

Everything works fine at runtime, all bindings work etc, so this is only a designer issue, so Im not sure if this is the correct place to report the bug. 

But maybe there is something that can be changed to fix it, like a build order or something?

### Steps to reproduce

```text
1. Create a new C# WPF project (I used .NET 6)
2, Add the Mvvm Toolkit Nuget package
3, Create a ViewModel class and set it as DataContext (MainWindow.xaml.cs)
4, Add any public Property to the ViewModel class and a field with [ObservableProperty]
5, Open the MainWindow.xaml and add d:DataContext="{d:DesignInstance Type=local:ViewModel}" to the Window element
6, Add a TextBox (or any other element which supports binding) and write <TextBox Text="{Binding 
7, Press open code completion list (CTRL + Space)
8, The list will contain the public property but NOT the property which was generated by [ObservableProperty]
```

### Expected behavior

The list should show both, the public property AND the property which was generated by [ObservableProperty]

### IDE and version

VS 2022

### IDE version

17.2.4

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

7.1.2

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment] 2022-07-09 12:10
This is a known issue with WPF, duplicate of #330.

**Closed by Sergio0694** 2022-07-09 12:10 UTC
Labels: external :arrow_heading_up:, mvvm-toolkit :toolbox:

**Comment by AignerGames** [comment] 2022-07-09 20:19
Im not sure if this is the same issue, the other post talks about build errors. I don't get any build errors, my build and runtime works fine, the only issue is the missing enty in the XAML designer list.

The linked post also mentions "upgrade to an SDK-style .NET 6 WPF project.". Im not sure what "SDK-style" means, but my project is already created with the .NET 6 template.

**Comment by micahmo** [comment] 2023-04-28 13:44
@Sergio0694 May we re-open this issue?

1. This is not a dupe of [#330](https://github.com/CommunityToolkit/dotnet/issues/330) (which is also closed as dupe). That one mentions build errors in .NET Framework. This issue is more of an edit-time inconvenience that looks bad in the XAML editor and prevents navigation.
2. [#330](https://github.com/CommunityToolkit/dotnet/issues/330) is linked to [#158](https://github.com/CommunityToolkit/dotnet/issues/158). That may be more similar, but it also mentions non-SDK style projects, which is not the case here.

I don't see any other open issue tracking this problem.
